package crypto

import (
	"encoding/hex"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Test vectors generated by Python's derive_key_hkdf() — if these fail,
// the Go and Python implementations have diverged.
func TestDeriveKeyMatchesPython(t *testing.T) {
	// Generate expected values from Python:
	//   from util.security.secret import derive_key_hkdf
	//   derive_key_hkdf("test1234").hex()
	tests := []struct {
		configKey   string
		expectedHex string
	}{
		{"test1234", "e72def9b0331ea29c2e7524d116bce03d6a1da2660eaa47b9dac81126e8a5f11"},
	}

	for _, tt := range tests {
		if tt.expectedHex == "" {
			t.Skipf("fill in expected hex for %q from Python's derive_key_hkdf()", tt.configKey)
		}
		key, err := DeriveKey(tt.configKey)
		require.NoError(t, err)
		assert.Equal(t, tt.expectedHex, hex.EncodeToString(key))
	}
}

// Cross-language test: decrypt values that were encrypted by Python.
func TestDecryptPythonValues(t *testing.T) {
	tests := []struct {
		name      string
		configKey string
		encrypted string
		expected  string
	}{
		{
			name:      "empty string",
			configKey: "test1234",
			encrypted: "v1$$KeHii9PxEjCRCz0vP+7+492VY29BypjJWesd/w==",
			expected:  "",
		},
		{
			name:      "hello world",
			configKey: "test1234",
			encrypted: "v1$$ycGiFF7IH9QmsxHoVRRkFzHSkR0cTthX1neza30kHGmpTXVypT3k",
			expected:  "hello world",
		},
		{
			name:      "binary key",
			configKey: "\x01\x02\x03\x04\x05\x06",
			encrypted: "v1$$zHTuvZ3QxWdYt9G5EFLgKm2V9/4Ys8Zrz6BSusy/wnf5fwVVXY39NMc2p20M/w==",
			expected:  "hello world, again",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			plaintext, err := Decrypt(tt.configKey, tt.encrypted)
			require.NoError(t, err)
			assert.Equal(t, tt.expected, plaintext)
		})
	}
}

func TestRoundTrip(t *testing.T) {
	values := []string{
		"",
		"hello world",
		"robot-token-abc123",
		"a]Sdf8!@#$%^&*()",
		strings.Repeat("a", 200),
	}

	for _, v := range values {
		t.Run(v, func(t *testing.T) {
			encrypted, err := Encrypt("test-secret", v)
			require.NoError(t, err)
			assert.True(t, strings.HasPrefix(encrypted, "v1$$"))

			decrypted, err := Decrypt("test-secret", encrypted)
			require.NoError(t, err)
			assert.Equal(t, v, decrypted)
		})
	}
}

func TestDecryptRejectsV0(t *testing.T) {
	_, err := Decrypt("test1234", "v0$$iE+87Qefu/2i+5zC87nlUtOskypk8MUUDS/QZPs=")
	require.Error(t, err)
	assert.Contains(t, err.Error(), "unsupported version prefix: v0")
}

func TestDecryptWrongKey(t *testing.T) {
	encrypted, err := Encrypt("correct-key", "secret data")
	require.NoError(t, err)

	_, err = Decrypt("wrong-key", encrypted)
	require.Error(t, err)
}

func TestNormalizeSecretKey(t *testing.T) {
	// Integer key
	raw, err := NormalizeSecretKey("255")
	require.NoError(t, err)
	assert.Equal(t, []byte{0xff}, raw)

	// String key
	raw, err = NormalizeSecretKey("test1234")
	require.NoError(t, err)
	assert.Equal(t, []byte("test1234"), raw)

	// Empty key
	_, err = NormalizeSecretKey("")
	require.Error(t, err)
}
