#! /bin/bash

echo 'Starting internal build manager'

# Run the build manager.
QUAYPATH=${QUAYPATH:-"."}
cd ${QUAYDIR:-"/"}
export PYTHONPATH=$QUAYPATH
exec venv/bin/python -m buildman.builder 2>&1

echo 'Internal build manager exited'
