version: "2"
run:
  go: "1.24"
  tests: true
linters:
  enable:
    - bodyclose
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - nilerr
    - nilnil
    - noctx
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - commentedOutCode
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
    govet:
      disable:
        - shadow
        - fieldalignment
      enable-all: true
    misspell:
      locale: US
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: exported
          severity: warning
        - name: unexported-return
          severity: warning
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
          severity: warning
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: superfluous-else
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - goconst
          - gocyclo
          - gosec
        path: _test\.go
      - linters:
          - gosec
        path: _test\.go
        text: 'G404:'
      - linters:
          - all
        path: .*\.pb\.go
    paths:
      - .*\.pb\.go$
      - vendor
      - config-tool
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go$
      - vendor
      - config-tool
      - third_party$
      - builtin$
      - examples$
