FROM quay-ci-base
RUN mkdir -p conf/stack
RUN rm -rf test/data/test.db
ADD cirun.config.yaml conf/stack/config.yaml
RUN LOGGING_LEVEL=INFO python initdb.py && \
    yum install -y make
ENTRYPOINT ["/quay-registry/quay-entrypoint.sh"]
CMD ["registry"]
