FROM registry.access.redhat.com/ubi9/go-toolset:9.8 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ cmd/
COPY internal/ internal/
USER 0
RUN CGO_ENABLED=0 go build -o /mirror-registry ./cmd/mirror-registry

FROM registry.access.redhat.com/ubi9/ubi-micro:latest
COPY --from=builder /mirror-registry /mirror-registry
EXPOSE 8443
ENTRYPOINT ["/mirror-registry"]
