FROM golang:1.26 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /quay ./cmd/quay

FROM scratch
COPY --from=builder /quay /quay
EXPOSE 8443
ENTRYPOINT ["/quay"]
