FROM golang:1.25 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /quay ./cmd/quay

FROM scratch
COPY --from=builder /quay /quay
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
USER 1001:0
EXPOSE 8443
ENTRYPOINT ["/quay"]
