// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: gc.sql

package daldb

import (
	"context"
	"database/sql"
)

const countBlobsByChecksum = `-- name: CountBlobsByChecksum :one
SELECT COUNT(*) FROM imagestorage WHERE content_checksum = ?
`

func (q *Queries) CountBlobsByChecksum(ctx context.Context, contentChecksum sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBlobsByChecksum, contentChecksum)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteExpiredTag = `-- name: DeleteExpiredTag :exec
DELETE FROM tag WHERE id = ?
`

func (q *Queries) DeleteExpiredTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredTag, id)
	return err
}

const deleteImageStoragePlacements = `-- name: DeleteImageStoragePlacements :exec
DELETE FROM imagestorageplacement WHERE storage_id = ?
`

func (q *Queries) DeleteImageStoragePlacements(ctx context.Context, storageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteImageStoragePlacements, storageID)
	return err
}

const deleteImageStorageSignatures = `-- name: DeleteImageStorageSignatures :exec
DELETE FROM imagestoragesignature WHERE storage_id = ?
`

func (q *Queries) DeleteImageStorageSignatures(ctx context.Context, storageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteImageStorageSignatures, storageID)
	return err
}

const deleteTagNotifications = `-- name: DeleteTagNotifications :exec
DELETE FROM tagnotificationsuccess WHERE tag_id = ?
`

func (q *Queries) DeleteTagNotifications(ctx context.Context, tagID int64) error {
	_, err := q.db.ExecContext(ctx, deleteTagNotifications, tagID)
	return err
}

const deleteUploadedBlobsByBlobID = `-- name: DeleteUploadedBlobsByBlobID :exec
DELETE FROM uploadedblob WHERE blob_id = ?
`

func (q *Queries) DeleteUploadedBlobsByBlobID(ctx context.Context, blobID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUploadedBlobsByBlobID, blobID)
	return err
}

const findExpiredTags = `-- name: FindExpiredTags :many
SELECT t.id, t.name, t.repository_id, t.manifest_id
FROM tag t
JOIN repository r ON t.repository_id = r.id
JOIN "user" u ON r.namespace_user_id = u.id
WHERE t.lifetime_end_ms IS NOT NULL
  AND t.lifetime_end_ms <= (
    (strftime('%s', 'now') * 1000) - (u.removed_tag_expiration_s * 1000)
  )
`

type FindExpiredTagsRow struct {
	ID           int64         `json:"id"`
	Name         string        `json:"name"`
	RepositoryID int64         `json:"repository_id"`
	ManifestID   sql.NullInt64 `json:"manifest_id"`
}

// Returns tags whose soft-delete grace period has elapsed.
// A tag is expired when lifetime_end_ms is set AND enough time has passed
// per the owning namespace's removed_tag_expiration_s setting.
func (q *Queries) FindExpiredTags(ctx context.Context) ([]FindExpiredTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, findExpiredTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindExpiredTagsRow
	for rows.Next() {
		var i FindExpiredTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepositoryID,
			&i.ManifestID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrphanedManifests = `-- name: FindOrphanedManifests :many
SELECT m.id, m.repository_id, m.digest
FROM manifest m
WHERE NOT EXISTS (
    SELECT 1 FROM tag t
    WHERE t.manifest_id = m.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM manifestchild mc
    WHERE mc.child_manifest_id = m.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM manifest m2
    WHERE m2.subject = m.digest
  )
`

type FindOrphanedManifestsRow struct {
	ID           int64  `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
}

// Returns manifests with no tags at all (neither live nor within grace period),
// not referenced as a child by any manifest list (globally, not repo-scoped),
// and not a subject target of any other manifest (OCI referrers, globally).
// IMPORTANT: This checks for ANY tag, including expired-but-within-grace-period
// tags. This is intentional. Phase 1 runs first and deletes only tags past their
// grace period. Any tag still present here (live or within grace) must protect
// the manifest. Do NOT add "AND lifetime_end_ms IS NULL" as that would allow
// manifests to be deleted while their tags are still recoverable.
func (q *Queries) FindOrphanedManifests(ctx context.Context) ([]FindOrphanedManifestsRow, error) {
	rows, err := q.db.QueryContext(ctx, findOrphanedManifests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOrphanedManifestsRow
	for rows.Next() {
		var i FindOrphanedManifestsRow
		if err := rows.Scan(&i.ID, &i.RepositoryID, &i.Digest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOrphanedManifestsByRepo = `-- name: FindOrphanedManifestsByRepo :many
SELECT m.id, m.repository_id, m.digest
FROM manifest m
WHERE m.repository_id = ?
  AND NOT EXISTS (
    SELECT 1 FROM tag t
    WHERE t.manifest_id = m.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM manifestchild mc
    WHERE mc.child_manifest_id = m.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM manifest m2
    WHERE m2.subject = m.digest
  )
`

type FindOrphanedManifestsByRepoRow struct {
	ID           int64  `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
}

// Same as FindOrphanedManifests but scoped to a single repository.
func (q *Queries) FindOrphanedManifestsByRepo(ctx context.Context, repositoryID int64) ([]FindOrphanedManifestsByRepoRow, error) {
	rows, err := q.db.QueryContext(ctx, findOrphanedManifestsByRepo, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOrphanedManifestsByRepoRow
	for rows.Next() {
		var i FindOrphanedManifestsByRepoRow
		if err := rows.Scan(&i.ID, &i.RepositoryID, &i.Digest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryIDs = `-- name: ListRepositoryIDs :many
SELECT id FROM repository WHERE state != 3
`

func (q *Queries) ListRepositoryIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listRepositoryIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
