// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: manifest.sql

package daldb

import (
	"context"
)

const countManifests = `-- name: CountManifests :one
SELECT COUNT(*) FROM manifest
`

func (q *Queries) CountManifests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countManifests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteManifest = `-- name: DeleteManifest :exec
DELETE FROM manifest WHERE id = ?
`

func (q *Queries) DeleteManifest(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteManifest, id)
	return err
}

const deleteManifestBlobs = `-- name: DeleteManifestBlobs :exec
DELETE FROM manifestblob WHERE manifest_id = ?
`

func (q *Queries) DeleteManifestBlobs(ctx context.Context, manifestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteManifestBlobs, manifestID)
	return err
}

const deleteManifestChildren = `-- name: DeleteManifestChildren :exec
DELETE FROM manifestchild WHERE manifest_id = ? OR child_manifest_id = ?
`

type DeleteManifestChildrenParams struct {
	ManifestID      int64 `json:"manifest_id"`
	ChildManifestID int64 `json:"child_manifest_id"`
}

func (q *Queries) DeleteManifestChildren(ctx context.Context, arg DeleteManifestChildrenParams) error {
	_, err := q.db.ExecContext(ctx, deleteManifestChildren, arg.ManifestID, arg.ChildManifestID)
	return err
}

const deleteManifestLabels = `-- name: DeleteManifestLabels :exec
DELETE FROM manifestlabel WHERE manifest_id = ?
`

func (q *Queries) DeleteManifestLabels(ctx context.Context, manifestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteManifestLabels, manifestID)
	return err
}

const deleteManifestSecurityStatus = `-- name: DeleteManifestSecurityStatus :exec
DELETE FROM manifestsecuritystatus WHERE manifest_id = ?
`

func (q *Queries) DeleteManifestSecurityStatus(ctx context.Context, manifestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteManifestSecurityStatus, manifestID)
	return err
}

const getManifestByDigest = `-- name: GetManifestByDigest :one
SELECT id, repository_id, digest, media_type_id, manifest_bytes
FROM manifest
WHERE repository_id = ? AND digest = ?
`

type GetManifestByDigestParams struct {
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
}

type GetManifestByDigestRow struct {
	ID            int64  `json:"id"`
	RepositoryID  int64  `json:"repository_id"`
	Digest        string `json:"digest"`
	MediaTypeID   int64  `json:"media_type_id"`
	ManifestBytes string `json:"manifest_bytes"`
}

func (q *Queries) GetManifestByDigest(ctx context.Context, arg GetManifestByDigestParams) (GetManifestByDigestRow, error) {
	row := q.db.QueryRowContext(ctx, getManifestByDigest, arg.RepositoryID, arg.Digest)
	var i GetManifestByDigestRow
	err := row.Scan(
		&i.ID,
		&i.RepositoryID,
		&i.Digest,
		&i.MediaTypeID,
		&i.ManifestBytes,
	)
	return i, err
}

const getManifestContentByDigest = `-- name: GetManifestContentByDigest :one
SELECT manifest_bytes FROM manifest WHERE digest = ? LIMIT 1
`

func (q *Queries) GetManifestContentByDigest(ctx context.Context, digest string) (string, error) {
	row := q.db.QueryRowContext(ctx, getManifestContentByDigest, digest)
	var manifest_bytes string
	err := row.Scan(&manifest_bytes)
	return manifest_bytes, err
}

const linkManifestBlob = `-- name: LinkManifestBlob :exec
INSERT OR IGNORE INTO manifestblob (repository_id, manifest_id, blob_id)
VALUES (?, ?, ?)
`

type LinkManifestBlobParams struct {
	RepositoryID int64 `json:"repository_id"`
	ManifestID   int64 `json:"manifest_id"`
	BlobID       int64 `json:"blob_id"`
}

func (q *Queries) LinkManifestBlob(ctx context.Context, arg LinkManifestBlobParams) error {
	_, err := q.db.ExecContext(ctx, linkManifestBlob, arg.RepositoryID, arg.ManifestID, arg.BlobID)
	return err
}

const linkManifestChild = `-- name: LinkManifestChild :exec
INSERT OR IGNORE INTO manifestchild (repository_id, manifest_id, child_manifest_id)
VALUES (?, ?, ?)
`

type LinkManifestChildParams struct {
	RepositoryID    int64 `json:"repository_id"`
	ManifestID      int64 `json:"manifest_id"`
	ChildManifestID int64 `json:"child_manifest_id"`
}

func (q *Queries) LinkManifestChild(ctx context.Context, arg LinkManifestChildParams) error {
	_, err := q.db.ExecContext(ctx, linkManifestChild, arg.RepositoryID, arg.ManifestID, arg.ChildManifestID)
	return err
}

const manifestExistsByDigest = `-- name: ManifestExistsByDigest :one
SELECT digest FROM manifest WHERE repository_id = ? AND digest = ?
`

type ManifestExistsByDigestParams struct {
	RepositoryID int64  `json:"repository_id"`
	Digest       string `json:"digest"`
}

func (q *Queries) ManifestExistsByDigest(ctx context.Context, arg ManifestExistsByDigestParams) (string, error) {
	row := q.db.QueryRowContext(ctx, manifestExistsByDigest, arg.RepositoryID, arg.Digest)
	var digest string
	err := row.Scan(&digest)
	return digest, err
}

const upsertManifest = `-- name: UpsertManifest :one
INSERT INTO manifest (repository_id, digest, media_type_id, manifest_bytes)
VALUES (?, ?, ?, ?)
ON CONFLICT (repository_id, digest) DO UPDATE SET manifest_bytes = excluded.manifest_bytes
RETURNING id
`

type UpsertManifestParams struct {
	RepositoryID  int64  `json:"repository_id"`
	Digest        string `json:"digest"`
	MediaTypeID   int64  `json:"media_type_id"`
	ManifestBytes string `json:"manifest_bytes"`
}

func (q *Queries) UpsertManifest(ctx context.Context, arg UpsertManifestParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertManifest,
		arg.RepositoryID,
		arg.Digest,
		arg.MediaTypeID,
		arg.ManifestBytes,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
