// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package daldb

import (
	"database/sql"
	"time"
)

type Accesstoken struct {
	ID           int64          `json:"id"`
	FriendlyName sql.NullString `json:"friendly_name"`
	RepositoryID int64          `json:"repository_id"`
	Created      time.Time      `json:"created"`
	RoleID       int64          `json:"role_id"`
	Temporary    bool           `json:"temporary"`
	KindID       sql.NullInt64  `json:"kind_id"`
	TokenCode    string         `json:"token_code"`
	TokenName    string         `json:"token_name"`
}

type Accesstokenkind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type AlembicVersion struct {
	VersionNum string `json:"version_num"`
}

type Apprblob struct {
	ID               int64         `json:"id"`
	Digest           string        `json:"digest"`
	MediaTypeID      int64         `json:"media_type_id"`
	Size             int64         `json:"size"`
	UncompressedSize sql.NullInt64 `json:"uncompressed_size"`
}

type Apprblobplacement struct {
	ID         int64 `json:"id"`
	BlobID     int64 `json:"blob_id"`
	LocationID int64 `json:"location_id"`
}

type Apprblobplacementlocation struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Apprmanifest struct {
	ID           int64  `json:"id"`
	Digest       string `json:"digest"`
	MediaTypeID  int64  `json:"media_type_id"`
	ManifestJson string `json:"manifest_json"`
}

type Apprmanifestblob struct {
	ID         int64 `json:"id"`
	ManifestID int64 `json:"manifest_id"`
	BlobID     int64 `json:"blob_id"`
}

type Apprmanifestlist struct {
	ID               int64  `json:"id"`
	Digest           string `json:"digest"`
	ManifestListJson string `json:"manifest_list_json"`
	SchemaVersion    string `json:"schema_version"`
	MediaTypeID      int64  `json:"media_type_id"`
}

type Apprmanifestlistmanifest struct {
	ID              int64          `json:"id"`
	ManifestListID  int64          `json:"manifest_list_id"`
	ManifestID      int64          `json:"manifest_id"`
	OperatingSystem sql.NullString `json:"operating_system"`
	Architecture    sql.NullString `json:"architecture"`
	PlatformJson    sql.NullString `json:"platform_json"`
	MediaTypeID     int64          `json:"media_type_id"`
}

type Apprtag struct {
	ID             int64         `json:"id"`
	Name           string        `json:"name"`
	RepositoryID   int64         `json:"repository_id"`
	ManifestListID sql.NullInt64 `json:"manifest_list_id"`
	LifetimeStart  int64         `json:"lifetime_start"`
	LifetimeEnd    sql.NullInt64 `json:"lifetime_end"`
	Hidden         bool          `json:"hidden"`
	Reverted       bool          `json:"reverted"`
	Protected      bool          `json:"protected"`
	TagKindID      int64         `json:"tag_kind_id"`
	LinkedTagID    sql.NullInt64 `json:"linked_tag_id"`
}

type Apprtagkind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Appspecificauthtoken struct {
	ID           int64        `json:"id"`
	UserID       int64        `json:"user_id"`
	Uuid         string       `json:"uuid"`
	Title        string       `json:"title"`
	Created      time.Time    `json:"created"`
	Expiration   sql.NullTime `json:"expiration"`
	LastAccessed sql.NullTime `json:"last_accessed"`
	TokenName    string       `json:"token_name"`
	TokenSecret  string       `json:"token_secret"`
}

type Autoprunetaskstatus struct {
	ID          int64          `json:"id"`
	NamespaceID int64          `json:"namespace_id"`
	LastRanMs   sql.NullInt64  `json:"last_ran_ms"`
	Status      sql.NullString `json:"status"`
}

type Blobupload struct {
	ID                    int64          `json:"id"`
	RepositoryID          int64          `json:"repository_id"`
	Uuid                  string         `json:"uuid"`
	ByteCount             int64          `json:"byte_count"`
	ShaState              sql.NullString `json:"sha_state"`
	LocationID            int64          `json:"location_id"`
	StorageMetadata       sql.NullString `json:"storage_metadata"`
	ChunkCount            int64          `json:"chunk_count"`
	UncompressedByteCount sql.NullInt64  `json:"uncompressed_byte_count"`
	Created               time.Time      `json:"created"`
	PieceShaState         sql.NullString `json:"piece_sha_state"`
	PieceHashes           sql.NullString `json:"piece_hashes"`
}

type Buildtriggerservice struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Deletednamespace struct {
	ID               int64          `json:"id"`
	NamespaceID      int64          `json:"namespace_id"`
	Marked           time.Time      `json:"marked"`
	OriginalUsername string         `json:"original_username"`
	OriginalEmail    string         `json:"original_email"`
	QueueID          sql.NullString `json:"queue_id"`
}

type Deletedrepository struct {
	ID           int64          `json:"id"`
	RepositoryID int64          `json:"repository_id"`
	Marked       time.Time      `json:"marked"`
	OriginalName string         `json:"original_name"`
	QueueID      sql.NullString `json:"queue_id"`
}

type Disablereason struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Emailconfirmation struct {
	ID               int64          `json:"id"`
	Code             string         `json:"code"`
	UserID           int64          `json:"user_id"`
	PwReset          bool           `json:"pw_reset"`
	NewEmail         sql.NullString `json:"new_email"`
	EmailConfirm     bool           `json:"email_confirm"`
	Created          time.Time      `json:"created"`
	VerificationCode sql.NullString `json:"verification_code"`
}

type Externalnotificationevent struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Externalnotificationmethod struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Federatedlogin struct {
	ID           int64  `json:"id"`
	UserID       int64  `json:"user_id"`
	ServiceID    int64  `json:"service_id"`
	ServiceIdent string `json:"service_ident"`
	MetadataJson string `json:"metadata_json"`
}

type Imagestorage struct {
	ID               int64          `json:"id"`
	Uuid             string         `json:"uuid"`
	ImageSize        sql.NullInt64  `json:"image_size"`
	UncompressedSize sql.NullInt64  `json:"uncompressed_size"`
	Uploading        sql.NullBool   `json:"uploading"`
	CasPath          bool           `json:"cas_path"`
	ContentChecksum  sql.NullString `json:"content_checksum"`
}

type Imagestoragelocation struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Imagestorageplacement struct {
	ID         int64 `json:"id"`
	StorageID  int64 `json:"storage_id"`
	LocationID int64 `json:"location_id"`
}

type Imagestoragesignature struct {
	ID        int64          `json:"id"`
	StorageID int64          `json:"storage_id"`
	KindID    int64          `json:"kind_id"`
	Signature sql.NullString `json:"signature"`
	Uploading sql.NullBool   `json:"uploading"`
}

type Imagestoragesignaturekind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Imagestoragetransformation struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Label struct {
	ID           int64  `json:"id"`
	Uuid         string `json:"uuid"`
	Key          string `json:"key"`
	Value        string `json:"value"`
	MediaTypeID  int64  `json:"media_type_id"`
	SourceTypeID int64  `json:"source_type_id"`
}

type Labelsourcetype struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Mutable bool   `json:"mutable"`
}

type Logentry struct {
	ID           int64          `json:"id"`
	KindID       int64          `json:"kind_id"`
	AccountID    int64          `json:"account_id"`
	PerformerID  sql.NullInt64  `json:"performer_id"`
	RepositoryID sql.NullInt64  `json:"repository_id"`
	Datetime     time.Time      `json:"datetime"`
	Ip           sql.NullString `json:"ip"`
	MetadataJson string         `json:"metadata_json"`
}

type Logentry2 struct {
	ID           int64          `json:"id"`
	KindID       int64          `json:"kind_id"`
	AccountID    int64          `json:"account_id"`
	PerformerID  sql.NullInt64  `json:"performer_id"`
	RepositoryID sql.NullInt64  `json:"repository_id"`
	Datetime     time.Time      `json:"datetime"`
	Ip           sql.NullString `json:"ip"`
	MetadataJson string         `json:"metadata_json"`
}

type Logentry3 struct {
	ID           int64          `json:"id"`
	KindID       int64          `json:"kind_id"`
	AccountID    int64          `json:"account_id"`
	PerformerID  sql.NullInt64  `json:"performer_id"`
	RepositoryID sql.NullInt64  `json:"repository_id"`
	Datetime     time.Time      `json:"datetime"`
	Ip           sql.NullString `json:"ip"`
	MetadataJson string         `json:"metadata_json"`
}

type Logentrykind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Loginservice struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Manifest struct {
	ID                     int64          `json:"id"`
	RepositoryID           int64          `json:"repository_id"`
	Digest                 string         `json:"digest"`
	MediaTypeID            int64          `json:"media_type_id"`
	ManifestBytes          string         `json:"manifest_bytes"`
	ConfigMediaType        sql.NullString `json:"config_media_type"`
	LayersCompressedSize   sql.NullInt64  `json:"layers_compressed_size"`
	Subject                sql.NullString `json:"subject"`
	SubjectBackfilled      sql.NullBool   `json:"subject_backfilled"`
	ArtifactType           sql.NullString `json:"artifact_type"`
	ArtifactTypeBackfilled sql.NullBool   `json:"artifact_type_backfilled"`
}

type Manifestblob struct {
	ID           int64 `json:"id"`
	RepositoryID int64 `json:"repository_id"`
	ManifestID   int64 `json:"manifest_id"`
	BlobID       int64 `json:"blob_id"`
}

type Manifestchild struct {
	ID              int64 `json:"id"`
	RepositoryID    int64 `json:"repository_id"`
	ManifestID      int64 `json:"manifest_id"`
	ChildManifestID int64 `json:"child_manifest_id"`
}

type Manifestlabel struct {
	ID           int64 `json:"id"`
	RepositoryID int64 `json:"repository_id"`
	ManifestID   int64 `json:"manifest_id"`
	LabelID      int64 `json:"label_id"`
}

type Manifestpullstatistic struct {
	ID                   int64     `json:"id"`
	RepositoryID         int64     `json:"repository_id"`
	ManifestDigest       string    `json:"manifest_digest"`
	ManifestPullCount    int64     `json:"manifest_pull_count"`
	LastManifestPullDate time.Time `json:"last_manifest_pull_date"`
}

type Manifestsecuritystatus struct {
	ID             int64     `json:"id"`
	ManifestID     int64     `json:"manifest_id"`
	RepositoryID   int64     `json:"repository_id"`
	IndexStatus    int64     `json:"index_status"`
	ErrorJson      string    `json:"error_json"`
	LastIndexed    time.Time `json:"last_indexed"`
	IndexerHash    string    `json:"indexer_hash"`
	IndexerVersion int64     `json:"indexer_version"`
	MetadataJson   string    `json:"metadata_json"`
}

type Mediatype struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Message struct {
	ID          int64  `json:"id"`
	Content     string `json:"content"`
	Uuid        string `json:"uuid"`
	MediaTypeID int64  `json:"media_type_id"`
	Severity    string `json:"severity"`
}

type Namespaceautoprunepolicy struct {
	ID          int64  `json:"id"`
	Uuid        string `json:"uuid"`
	NamespaceID int64  `json:"namespace_id"`
	Policy      string `json:"policy"`
}

type Namespaceimmutabilitypolicy struct {
	ID          int64  `json:"id"`
	Uuid        string `json:"uuid"`
	NamespaceID int64  `json:"namespace_id"`
	Policy      string `json:"policy"`
}

type Notification struct {
	ID           int64          `json:"id"`
	Uuid         string         `json:"uuid"`
	KindID       int64          `json:"kind_id"`
	TargetID     int64          `json:"target_id"`
	MetadataJson string         `json:"metadata_json"`
	Created      time.Time      `json:"created"`
	Dismissed    bool           `json:"dismissed"`
	LookupPath   sql.NullString `json:"lookup_path"`
}

type Notificationkind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Oauthaccesstoken struct {
	ID               int64     `json:"id"`
	Uuid             string    `json:"uuid"`
	ApplicationID    int64     `json:"application_id"`
	AuthorizedUserID int64     `json:"authorized_user_id"`
	Scope            string    `json:"scope"`
	TokenType        string    `json:"token_type"`
	ExpiresAt        time.Time `json:"expires_at"`
	Data             string    `json:"data"`
	TokenCode        string    `json:"token_code"`
	TokenName        string    `json:"token_name"`
}

type Oauthapplication struct {
	ID                 int64          `json:"id"`
	ClientID           string         `json:"client_id"`
	RedirectUri        string         `json:"redirect_uri"`
	ApplicationUri     string         `json:"application_uri"`
	OrganizationID     int64          `json:"organization_id"`
	Name               string         `json:"name"`
	Description        string         `json:"description"`
	GravatarEmail      sql.NullString `json:"gravatar_email"`
	SecureClientSecret sql.NullString `json:"secure_client_secret"`
	FullyMigrated      bool           `json:"fully_migrated"`
}

type Oauthassignedtoken struct {
	ID             int64          `json:"id"`
	Uuid           string         `json:"uuid"`
	AssignedUserID int64          `json:"assigned_user_id"`
	ApplicationID  int64          `json:"application_id"`
	RedirectUri    sql.NullString `json:"redirect_uri"`
	Scope          string         `json:"scope"`
	ResponseType   sql.NullString `json:"response_type"`
}

type Oauthauthorizationcode struct {
	ID             int64  `json:"id"`
	ApplicationID  int64  `json:"application_id"`
	Scope          string `json:"scope"`
	Data           string `json:"data"`
	CodeCredential string `json:"code_credential"`
	CodeName       string `json:"code_name"`
}

type Organizationcontactemail struct {
	ID             int64          `json:"id"`
	OrganizationID int64          `json:"organization_id"`
	ContactEmail   sql.NullString `json:"contact_email"`
}

type Organizationrhsku struct {
	ID             int64         `json:"id"`
	SubscriptionID int64         `json:"subscription_id"`
	OrgID          int64         `json:"org_id"`
	UserID         int64         `json:"user_id"`
	Quantity       sql.NullInt64 `json:"quantity"`
}

type Orgmirrorconfig struct {
	ID                       int64          `json:"id"`
	OrganizationID           int64          `json:"organization_id"`
	CreationDate             time.Time      `json:"creation_date"`
	IsEnabled                bool           `json:"is_enabled"`
	MirrorType               int64          `json:"mirror_type"`
	ExternalRegistryType     int64          `json:"external_registry_type"`
	ExternalRegistryUrl      string         `json:"external_registry_url"`
	ExternalNamespace        string         `json:"external_namespace"`
	ExternalRegistryUsername sql.NullString `json:"external_registry_username"`
	ExternalRegistryPassword sql.NullString `json:"external_registry_password"`
	ExternalRegistryConfig   string         `json:"external_registry_config"`
	InternalRobotID          int64          `json:"internal_robot_id"`
	RepositoryFilters        string         `json:"repository_filters"`
	VisibilityID             int64          `json:"visibility_id"`
	DeleteStaleRepos         bool           `json:"delete_stale_repos"`
	SyncInterval             int64          `json:"sync_interval"`
	SyncStartDate            sql.NullTime   `json:"sync_start_date"`
	SyncExpirationDate       sql.NullTime   `json:"sync_expiration_date"`
	SyncRetriesRemaining     int64          `json:"sync_retries_remaining"`
	SyncStatus               int64          `json:"sync_status"`
	SyncTransactionID        sql.NullString `json:"sync_transaction_id"`
	SkopeoTimeout            int64          `json:"skopeo_timeout"`
	ArchitectureFilter       string         `json:"architecture_filter"`
}

type Orgmirrorrepository struct {
	ID                   int64          `json:"id"`
	OrgMirrorConfigID    int64          `json:"org_mirror_config_id"`
	RepositoryName       string         `json:"repository_name"`
	RepositoryID         sql.NullInt64  `json:"repository_id"`
	DiscoveryDate        time.Time      `json:"discovery_date"`
	SyncStatus           int64          `json:"sync_status"`
	SyncStartDate        sql.NullTime   `json:"sync_start_date"`
	SyncExpirationDate   sql.NullTime   `json:"sync_expiration_date"`
	LastSyncDate         sql.NullTime   `json:"last_sync_date"`
	StatusMessage        sql.NullString `json:"status_message"`
	CreationDate         time.Time      `json:"creation_date"`
	SyncRetriesRemaining int64          `json:"sync_retries_remaining"`
	SyncTransactionID    sql.NullString `json:"sync_transaction_id"`
}

type Permissionprototype struct {
	ID               int64         `json:"id"`
	OrgID            int64         `json:"org_id"`
	Uuid             string        `json:"uuid"`
	ActivatingUserID sql.NullInt64 `json:"activating_user_id"`
	DelegateUserID   sql.NullInt64 `json:"delegate_user_id"`
	DelegateTeamID   sql.NullInt64 `json:"delegate_team_id"`
	RoleID           int64         `json:"role_id"`
}

type Proxycacheconfig struct {
	ID                       int64          `json:"id"`
	OrganizationID           int64          `json:"organization_id"`
	CreationDate             time.Time      `json:"creation_date"`
	UpstreamRegistry         string         `json:"upstream_registry"`
	UpstreamRegistryUsername sql.NullString `json:"upstream_registry_username"`
	UpstreamRegistryPassword sql.NullString `json:"upstream_registry_password"`
	ExpirationS              sql.NullInt64  `json:"expiration_s"`
	Insecure                 bool           `json:"insecure"`
}

type Quayregion struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Quayrelease struct {
	ID        int64     `json:"id"`
	ServiceID int64     `json:"service_id"`
	Version   string    `json:"version"`
	RegionID  int64     `json:"region_id"`
	Reverted  bool      `json:"reverted"`
	Created   time.Time `json:"created"`
}

type Quayservice struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Queueitem struct {
	ID                int64        `json:"id"`
	QueueName         string       `json:"queue_name"`
	Body              string       `json:"body"`
	AvailableAfter    time.Time    `json:"available_after"`
	Available         bool         `json:"available"`
	ProcessingExpires sql.NullTime `json:"processing_expires"`
	RetriesRemaining  int64        `json:"retries_remaining"`
	StateID           string       `json:"state_id"`
}

type Quotalimit struct {
	ID             int64 `json:"id"`
	QuotaID        int64 `json:"quota_id"`
	QuotaTypeID    int64 `json:"quota_type_id"`
	PercentOfLimit int64 `json:"percent_of_limit"`
}

type Quotanamespacesize struct {
	ID               int64         `json:"id"`
	NamespaceUserID  int64         `json:"namespace_user_id"`
	SizeBytes        int64         `json:"size_bytes"`
	BackfillStartMs  sql.NullInt64 `json:"backfill_start_ms"`
	BackfillComplete bool          `json:"backfill_complete"`
}

type Quotaregistrysize struct {
	ID          int64         `json:"id"`
	SizeBytes   int64         `json:"size_bytes"`
	Running     bool          `json:"running"`
	Queued      bool          `json:"queued"`
	CompletedMs sql.NullInt64 `json:"completed_ms"`
}

type Quotarepositorysize struct {
	ID               int64         `json:"id"`
	RepositoryID     int64         `json:"repository_id"`
	SizeBytes        int64         `json:"size_bytes"`
	BackfillStartMs  sql.NullInt64 `json:"backfill_start_ms"`
	BackfillComplete bool          `json:"backfill_complete"`
}

type Quotatype struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Redhatsubscription struct {
	ID            int64 `json:"id"`
	UserID        int64 `json:"user_id"`
	AccountNumber int64 `json:"account_number"`
}

type Repomirrorconfig struct {
	ID                       int64          `json:"id"`
	RepositoryID             int64          `json:"repository_id"`
	CreationDate             time.Time      `json:"creation_date"`
	IsEnabled                bool           `json:"is_enabled"`
	MirrorType               int64          `json:"mirror_type"`
	InternalRobotID          int64          `json:"internal_robot_id"`
	ExternalRegistryUsername sql.NullString `json:"external_registry_username"`
	ExternalRegistryConfig   string         `json:"external_registry_config"`
	SyncInterval             int64          `json:"sync_interval"`
	SyncStartDate            sql.NullTime   `json:"sync_start_date"`
	SyncExpirationDate       sql.NullTime   `json:"sync_expiration_date"`
	SyncRetriesRemaining     int64          `json:"sync_retries_remaining"`
	SyncStatus               int64          `json:"sync_status"`
	SyncTransactionID        sql.NullString `json:"sync_transaction_id"`
	RootRuleID               int64          `json:"root_rule_id"`
	ExternalReference        string         `json:"external_reference"`
	ExternalRegistryPassword sql.NullString `json:"external_registry_password"`
	SkopeoTimeout            int64          `json:"skopeo_timeout"`
	ArchitectureFilter       sql.NullString `json:"architecture_filter"`
}

type Repomirrorrule struct {
	ID           int64         `json:"id"`
	Uuid         string        `json:"uuid"`
	RepositoryID int64         `json:"repository_id"`
	CreationDate time.Time     `json:"creation_date"`
	RuleType     int64         `json:"rule_type"`
	RuleValue    string        `json:"rule_value"`
	LeftChildID  sql.NullInt64 `json:"left_child_id"`
	RightChildID sql.NullInt64 `json:"right_child_id"`
}

type Repository struct {
	ID              int64          `json:"id"`
	NamespaceUserID sql.NullInt64  `json:"namespace_user_id"`
	Name            string         `json:"name"`
	VisibilityID    int64          `json:"visibility_id"`
	Description     sql.NullString `json:"description"`
	BadgeToken      string         `json:"badge_token"`
	KindID          int64          `json:"kind_id"`
	TrustEnabled    bool           `json:"trust_enabled"`
	State           int64          `json:"state"`
}

type Repositoryactioncount struct {
	ID           int64     `json:"id"`
	RepositoryID int64     `json:"repository_id"`
	Count        int64     `json:"count"`
	Date         time.Time `json:"date"`
}

type Repositoryauthorizedemail struct {
	ID           int64  `json:"id"`
	RepositoryID int64  `json:"repository_id"`
	Email        string `json:"email"`
	Code         string `json:"code"`
	Confirmed    bool   `json:"confirmed"`
}

type Repositoryautoprunepolicy struct {
	ID           int64  `json:"id"`
	Uuid         string `json:"uuid"`
	RepositoryID int64  `json:"repository_id"`
	NamespaceID  int64  `json:"namespace_id"`
	Policy       string `json:"policy"`
}

type Repositorybuild struct {
	ID            int64          `json:"id"`
	Uuid          string         `json:"uuid"`
	RepositoryID  int64          `json:"repository_id"`
	AccessTokenID int64          `json:"access_token_id"`
	ResourceKey   sql.NullString `json:"resource_key"`
	JobConfig     string         `json:"job_config"`
	Phase         string         `json:"phase"`
	Started       time.Time      `json:"started"`
	DisplayName   string         `json:"display_name"`
	TriggerID     sql.NullInt64  `json:"trigger_id"`
	PullRobotID   sql.NullInt64  `json:"pull_robot_id"`
	LogsArchived  bool           `json:"logs_archived"`
	QueueID       sql.NullString `json:"queue_id"`
}

type Repositorybuildtrigger struct {
	ID                           int64          `json:"id"`
	Uuid                         string         `json:"uuid"`
	ServiceID                    int64          `json:"service_id"`
	RepositoryID                 int64          `json:"repository_id"`
	ConnectedUserID              int64          `json:"connected_user_id"`
	Config                       string         `json:"config"`
	WriteTokenID                 sql.NullInt64  `json:"write_token_id"`
	PullRobotID                  sql.NullInt64  `json:"pull_robot_id"`
	DisabledReasonID             sql.NullInt64  `json:"disabled_reason_id"`
	Enabled                      bool           `json:"enabled"`
	SuccessiveFailureCount       int64          `json:"successive_failure_count"`
	SuccessiveInternalErrorCount int64          `json:"successive_internal_error_count"`
	DisabledDatetime             sql.NullTime   `json:"disabled_datetime"`
	SecureAuthToken              sql.NullString `json:"secure_auth_token"`
	SecurePrivateKey             sql.NullString `json:"secure_private_key"`
	FullyMigrated                bool           `json:"fully_migrated"`
}

type Repositoryimmutabilitypolicy struct {
	ID           int64  `json:"id"`
	Uuid         string `json:"uuid"`
	RepositoryID int64  `json:"repository_id"`
	NamespaceID  int64  `json:"namespace_id"`
	Policy       string `json:"policy"`
}

type Repositorykind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Repositorynotification struct {
	ID               int64          `json:"id"`
	Uuid             string         `json:"uuid"`
	RepositoryID     int64          `json:"repository_id"`
	EventID          int64          `json:"event_id"`
	MethodID         int64          `json:"method_id"`
	Title            sql.NullString `json:"title"`
	ConfigJson       string         `json:"config_json"`
	EventConfigJson  string         `json:"event_config_json"`
	NumberOfFailures int64          `json:"number_of_failures"`
	LastRanMs        sql.NullInt64  `json:"last_ran_ms"`
}

type Repositorypermission struct {
	ID           int64         `json:"id"`
	TeamID       sql.NullInt64 `json:"team_id"`
	UserID       sql.NullInt64 `json:"user_id"`
	RepositoryID int64         `json:"repository_id"`
	RoleID       int64         `json:"role_id"`
}

type Repositorysearchscore struct {
	ID           int64        `json:"id"`
	RepositoryID int64        `json:"repository_id"`
	Score        int64        `json:"score"`
	LastUpdated  sql.NullTime `json:"last_updated"`
}

type Robotaccountmetadatum struct {
	ID               int64  `json:"id"`
	RobotAccountID   int64  `json:"robot_account_id"`
	Description      string `json:"description"`
	UnstructuredJson string `json:"unstructured_json"`
}

type Robotaccounttoken struct {
	ID             int64  `json:"id"`
	RobotAccountID int64  `json:"robot_account_id"`
	Token          string `json:"token"`
	FullyMigrated  bool   `json:"fully_migrated"`
}

type Role struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Servicekey struct {
	ID               int64         `json:"id"`
	Name             string        `json:"name"`
	Kid              string        `json:"kid"`
	Service          string        `json:"service"`
	Jwk              string        `json:"jwk"`
	Metadata         string        `json:"metadata"`
	CreatedDate      time.Time     `json:"created_date"`
	ExpirationDate   sql.NullTime  `json:"expiration_date"`
	RotationDuration sql.NullInt64 `json:"rotation_duration"`
	ApprovalID       sql.NullInt64 `json:"approval_id"`
}

type Servicekeyapproval struct {
	ID           int64         `json:"id"`
	ApproverID   sql.NullInt64 `json:"approver_id"`
	ApprovalType string        `json:"approval_type"`
	ApprovedDate time.Time     `json:"approved_date"`
	Notes        string        `json:"notes"`
}

type Star struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	RepositoryID int64     `json:"repository_id"`
	Created      time.Time `json:"created"`
}

type Tag struct {
	ID              int64         `json:"id"`
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	LifetimeEndMs   sql.NullInt64 `json:"lifetime_end_ms"`
	Hidden          bool          `json:"hidden"`
	Reversion       bool          `json:"reversion"`
	TagKindID       int64         `json:"tag_kind_id"`
	LinkedTagID     sql.NullInt64 `json:"linked_tag_id"`
	Immutable       bool          `json:"immutable"`
}

type Tagkind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Tagnotificationsuccess struct {
	ID             int64 `json:"id"`
	NotificationID int64 `json:"notification_id"`
	TagID          int64 `json:"tag_id"`
	MethodID       int64 `json:"method_id"`
}

type Tagpullstatistic struct {
	ID                    int64          `json:"id"`
	RepositoryID          int64          `json:"repository_id"`
	TagName               string         `json:"tag_name"`
	TagPullCount          int64          `json:"tag_pull_count"`
	LastTagPullDate       time.Time      `json:"last_tag_pull_date"`
	CurrentManifestDigest sql.NullString `json:"current_manifest_digest"`
}

type Team struct {
	ID             int64  `json:"id"`
	Name           string `json:"name"`
	OrganizationID int64  `json:"organization_id"`
	RoleID         int64  `json:"role_id"`
	Description    string `json:"description"`
}

type Teammember struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	TeamID int64 `json:"team_id"`
}

type Teammemberinvite struct {
	ID          int64          `json:"id"`
	UserID      sql.NullInt64  `json:"user_id"`
	Email       sql.NullString `json:"email"`
	TeamID      int64          `json:"team_id"`
	InviterID   int64          `json:"inviter_id"`
	InviteToken string         `json:"invite_token"`
}

type Teamrole struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Teamsync struct {
	ID            int64        `json:"id"`
	TeamID        int64        `json:"team_id"`
	TransactionID string       `json:"transaction_id"`
	LastUpdated   sql.NullTime `json:"last_updated"`
	ServiceID     int64        `json:"service_id"`
	Config        string       `json:"config"`
}

type Uploadedblob struct {
	ID           int64     `json:"id"`
	RepositoryID int64     `json:"repository_id"`
	BlobID       int64     `json:"blob_id"`
	UploadedAt   time.Time `json:"uploaded_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type User struct {
	ID                       int64          `json:"id"`
	Uuid                     sql.NullString `json:"uuid"`
	Username                 string         `json:"username"`
	PasswordHash             sql.NullString `json:"password_hash"`
	Email                    string         `json:"email"`
	Verified                 bool           `json:"verified"`
	StripeID                 sql.NullString `json:"stripe_id"`
	Organization             bool           `json:"organization"`
	Robot                    bool           `json:"robot"`
	InvoiceEmail             bool           `json:"invoice_email"`
	InvalidLoginAttempts     int64          `json:"invalid_login_attempts"`
	LastInvalidLogin         time.Time      `json:"last_invalid_login"`
	RemovedTagExpirationS    int64          `json:"removed_tag_expiration_s"`
	Enabled                  bool           `json:"enabled"`
	InvoiceEmailAddress      sql.NullString `json:"invoice_email_address"`
	Company                  sql.NullString `json:"company"`
	FamilyName               sql.NullString `json:"family_name"`
	GivenName                sql.NullString `json:"given_name"`
	Location                 sql.NullString `json:"location"`
	MaximumQueuedBuildsCount sql.NullInt64  `json:"maximum_queued_builds_count"`
	CreationDate             sql.NullTime   `json:"creation_date"`
	LastAccessed             sql.NullTime   `json:"last_accessed"`
}

type Userorganizationquotum struct {
	ID          int64 `json:"id"`
	NamespaceID int64 `json:"namespace_id"`
	LimitBytes  int64 `json:"limit_bytes"`
}

type Userprompt struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
	KindID int64 `json:"kind_id"`
}

type Userpromptkind struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Userregion struct {
	ID         int64 `json:"id"`
	UserID     int64 `json:"user_id"`
	LocationID int64 `json:"location_id"`
}

type Visibility struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
