// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repository.sql

package daldb

import (
	"context"
	"database/sql"
)

const countRepositories = `-- name: CountRepositories :one
SELECT COUNT(*) FROM repository
`

func (q *Queries) CountRepositories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRepositories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrCreateRepository = `-- name: GetOrCreateRepository :one
INSERT INTO repository (namespace_user_id, name, visibility_id, kind_id, badge_token, state)
VALUES (?, ?, ?, ?, ?, 0)
ON CONFLICT (namespace_user_id, name) DO UPDATE SET name = excluded.name
RETURNING id
`

type GetOrCreateRepositoryParams struct {
	NamespaceUserID sql.NullInt64 `json:"namespace_user_id"`
	Name            string        `json:"name"`
	VisibilityID    int64         `json:"visibility_id"`
	KindID          int64         `json:"kind_id"`
	BadgeToken      string        `json:"badge_token"`
}

func (q *Queries) GetOrCreateRepository(ctx context.Context, arg GetOrCreateRepositoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateRepository,
		arg.NamespaceUserID,
		arg.Name,
		arg.VisibilityID,
		arg.KindID,
		arg.BadgeToken,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getRepositoryByName = `-- name: GetRepositoryByName :one
SELECT id, namespace_user_id, name, visibility_id, kind_id, state
FROM repository
WHERE namespace_user_id = ? AND name = ?
`

type GetRepositoryByNameParams struct {
	NamespaceUserID sql.NullInt64 `json:"namespace_user_id"`
	Name            string        `json:"name"`
}

type GetRepositoryByNameRow struct {
	ID              int64         `json:"id"`
	NamespaceUserID sql.NullInt64 `json:"namespace_user_id"`
	Name            string        `json:"name"`
	VisibilityID    int64         `json:"visibility_id"`
	KindID          int64         `json:"kind_id"`
	State           int64         `json:"state"`
}

func (q *Queries) GetRepositoryByName(ctx context.Context, arg GetRepositoryByNameParams) (GetRepositoryByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByName, arg.NamespaceUserID, arg.Name)
	var i GetRepositoryByNameRow
	err := row.Scan(
		&i.ID,
		&i.NamespaceUserID,
		&i.Name,
		&i.VisibilityID,
		&i.KindID,
		&i.State,
	)
	return i, err
}

const getRepositoryByNamespaceName = `-- name: GetRepositoryByNamespaceName :one
SELECT r.id FROM repository r
JOIN "user" u ON r.namespace_user_id = u.id
WHERE u.username = ? AND r.name = ?
`

type GetRepositoryByNamespaceNameParams struct {
	Username string `json:"username"`
	Name     string `json:"name"`
}

func (q *Queries) GetRepositoryByNamespaceName(ctx context.Context, arg GetRepositoryByNamespaceNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByNamespaceName, arg.Username, arg.Name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAllRepositories = `-- name: ListAllRepositories :many
SELECT u.username AS namespace, r.name
FROM repository r
JOIN "user" u ON r.namespace_user_id = u.id
ORDER BY u.username, r.name
`

type ListAllRepositoriesRow struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

func (q *Queries) ListAllRepositories(ctx context.Context) ([]ListAllRepositoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRepositoriesRow
	for rows.Next() {
		var i ListAllRepositoriesRow
		if err := rows.Scan(&i.Namespace, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
