// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: storage.sql

package daldb

import (
	"context"
	"database/sql"
)

const blobLinkedToRepo = `-- name: BlobLinkedToRepo :one
SELECT 1 FROM imagestorage s
WHERE s.content_checksum = ? AND (
  EXISTS (SELECT 1 FROM manifestblob mb WHERE mb.blob_id = s.id AND mb.repository_id = ?)
  OR EXISTS (SELECT 1 FROM uploadedblob ub WHERE ub.blob_id = s.id AND ub.repository_id = ? AND ub.expires_at > datetime('now'))
)
`

type BlobLinkedToRepoParams struct {
	ContentChecksum sql.NullString `json:"content_checksum"`
	RepositoryID    int64          `json:"repository_id"`
	RepositoryID_2  int64          `json:"repository_id_2"`
}

// Matches Python's get_repository_blob_by_digest: checks both ManifestBlob
// and UploadedBlob (for recently pushed blobs not yet referenced by a manifest).
func (q *Queries) BlobLinkedToRepo(ctx context.Context, arg BlobLinkedToRepoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, blobLinkedToRepo, arg.ContentChecksum, arg.RepositoryID, arg.RepositoryID_2)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const cleanExpiredUploadedBlobs = `-- name: CleanExpiredUploadedBlobs :exec
DELETE FROM uploadedblob WHERE expires_at < datetime('now')
`

func (q *Queries) CleanExpiredUploadedBlobs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredUploadedBlobs)
	return err
}

const deleteImageStorage = `-- name: DeleteImageStorage :exec
DELETE FROM imagestorage WHERE id = ?
`

func (q *Queries) DeleteImageStorage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteImageStorage, id)
	return err
}

const findOrphanedBlobs = `-- name: FindOrphanedBlobs :many
SELECT s.id, s.content_checksum, s.uuid, s.image_size
FROM imagestorage s
WHERE s.uploading = 0
  AND s.id NOT IN (SELECT blob_id FROM manifestblob)
  AND s.id NOT IN (
    SELECT blob_id FROM uploadedblob WHERE expires_at > datetime('now')
  )
`

type FindOrphanedBlobsRow struct {
	ID              int64          `json:"id"`
	ContentChecksum sql.NullString `json:"content_checksum"`
	Uuid            string         `json:"uuid"`
	ImageSize       sql.NullInt64  `json:"image_size"`
}

func (q *Queries) FindOrphanedBlobs(ctx context.Context) ([]FindOrphanedBlobsRow, error) {
	rows, err := q.db.QueryContext(ctx, findOrphanedBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindOrphanedBlobsRow
	for rows.Next() {
		var i FindOrphanedBlobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContentChecksum,
			&i.Uuid,
			&i.ImageSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlobByChecksum = `-- name: GetBlobByChecksum :one
SELECT id FROM imagestorage WHERE content_checksum = ?
`

func (q *Queries) GetBlobByChecksum(ctx context.Context, contentChecksum sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBlobByChecksum, contentChecksum)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBlob = `-- name: InsertBlob :one
INSERT INTO imagestorage (uuid, content_checksum, image_size, uploading, cas_path)
VALUES (?, ?, ?, 0, 1)
ON CONFLICT (uuid) DO UPDATE SET content_checksum = excluded.content_checksum
RETURNING id
`

type InsertBlobParams struct {
	Uuid            string         `json:"uuid"`
	ContentChecksum sql.NullString `json:"content_checksum"`
	ImageSize       sql.NullInt64  `json:"image_size"`
}

func (q *Queries) InsertBlob(ctx context.Context, arg InsertBlobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertBlob, arg.Uuid, arg.ContentChecksum, arg.ImageSize)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertUploadedBlob = `-- name: InsertUploadedBlob :exec
INSERT OR IGNORE INTO uploadedblob (repository_id, blob_id, uploaded_at, expires_at)
VALUES (?, ?, datetime('now'), datetime('now', '+1 hour'))
`

type InsertUploadedBlobParams struct {
	RepositoryID int64 `json:"repository_id"`
	BlobID       int64 `json:"blob_id"`
}

func (q *Queries) InsertUploadedBlob(ctx context.Context, arg InsertUploadedBlobParams) error {
	_, err := q.db.ExecContext(ctx, insertUploadedBlob, arg.RepositoryID, arg.BlobID)
	return err
}

const totalStorageBytes = `-- name: TotalStorageBytes :one
SELECT COALESCE(SUM(image_size), 0) FROM imagestorage WHERE uploading = 0
`

func (q *Queries) TotalStorageBytes(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, totalStorageBytes)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}
