// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tag.sql

package daldb

import (
	"context"
	"database/sql"
)

const deleteTagsByManifest = `-- name: DeleteTagsByManifest :exec
DELETE FROM tag WHERE manifest_id = ?
`

func (q *Queries) DeleteTagsByManifest(ctx context.Context, manifestID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTagsByManifest, manifestID)
	return err
}

const expireActiveTag = `-- name: ExpireActiveTag :execresult
UPDATE tag SET lifetime_end_ms = ?
WHERE repository_id = ? AND name = ? AND lifetime_end_ms IS NULL
`

type ExpireActiveTagParams struct {
	LifetimeEndMs sql.NullInt64 `json:"lifetime_end_ms"`
	RepositoryID  int64         `json:"repository_id"`
	Name          string        `json:"name"`
}

func (q *Queries) ExpireActiveTag(ctx context.Context, arg ExpireActiveTagParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, expireActiveTag, arg.LifetimeEndMs, arg.RepositoryID, arg.Name)
}

const getActiveTagDigest = `-- name: GetActiveTagDigest :one
SELECT m.digest
FROM tag t
JOIN manifest m ON t.manifest_id = m.id
WHERE t.repository_id = ? AND t.name = ? AND t.lifetime_end_ms IS NULL
`

type GetActiveTagDigestParams struct {
	RepositoryID int64  `json:"repository_id"`
	Name         string `json:"name"`
}

func (q *Queries) GetActiveTagDigest(ctx context.Context, arg GetActiveTagDigestParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getActiveTagDigest, arg.RepositoryID, arg.Name)
	var digest string
	err := row.Scan(&digest)
	return digest, err
}

const getActiveTagLifetimeStart = `-- name: GetActiveTagLifetimeStart :one
SELECT lifetime_start_ms
FROM tag
WHERE repository_id = ? AND name = ? AND lifetime_end_ms IS NULL
ORDER BY lifetime_start_ms DESC
LIMIT 1
`

type GetActiveTagLifetimeStartParams struct {
	RepositoryID int64  `json:"repository_id"`
	Name         string `json:"name"`
}

func (q *Queries) GetActiveTagLifetimeStart(ctx context.Context, arg GetActiveTagLifetimeStartParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getActiveTagLifetimeStart, arg.RepositoryID, arg.Name)
	var lifetime_start_ms int64
	err := row.Scan(&lifetime_start_ms)
	return lifetime_start_ms, err
}

const getTagsByRepository = `-- name: GetTagsByRepository :many
SELECT id, name, repository_id, manifest_id, lifetime_start_ms, lifetime_end_ms, tag_kind_id
FROM tag
WHERE repository_id = ? AND lifetime_end_ms IS NULL AND hidden = 0
`

type GetTagsByRepositoryRow struct {
	ID              int64         `json:"id"`
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	LifetimeEndMs   sql.NullInt64 `json:"lifetime_end_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
}

func (q *Queries) GetTagsByRepository(ctx context.Context, repositoryID int64) ([]GetTagsByRepositoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTagsByRepositoryRow
	for rows.Next() {
		var i GetTagsByRepositoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepositoryID,
			&i.ManifestID,
			&i.LifetimeStartMs,
			&i.LifetimeEndMs,
			&i.TagKindID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasNonExpiringTagForManifest = `-- name: HasNonExpiringTagForManifest :one
SELECT EXISTS(
    SELECT 1 FROM tag WHERE manifest_id = ? AND lifetime_end_ms IS NULL
) AS has_tag
`

// Returns true if the manifest already has at least one non-expiring tag
// (lifetime_end_ms IS NULL). Used to skip creating duplicate protection tags.
func (q *Queries) HasNonExpiringTagForManifest(ctx context.Context, manifestID sql.NullInt64) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasNonExpiringTagForManifest, manifestID)
	var has_tag bool
	err := row.Scan(&has_tag)
	return has_tag, err
}

const hasUnexpiredTemporaryTag = `-- name: HasUnexpiredTemporaryTag :one
SELECT EXISTS (
    SELECT 1 FROM tag
    WHERE manifest_id = ?
    AND hidden = 1
    AND name LIKE '$temp-%'
    AND lifetime_end_ms > ?
) AS has_tag
`

type HasUnexpiredTemporaryTagParams struct {
	ManifestID    sql.NullInt64 `json:"manifest_id"`
	LifetimeEndMs sql.NullInt64 `json:"lifetime_end_ms"`
}

// Checks if we already have a temporary tag for a particular manifest.
// In addition to matching against a specific manifest, we also match by name where
// the name must be in the form '$temp-some_uuid'. This ensures that we don't match
// any tags that are properly alive.
func (q *Queries) HasUnexpiredTemporaryTag(ctx context.Context, arg HasUnexpiredTemporaryTagParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasUnexpiredTemporaryTag, arg.ManifestID, arg.LifetimeEndMs)
	var has_tag bool
	err := row.Scan(&has_tag)
	return has_tag, err
}

const insertHiddenTag = `-- name: InsertHiddenTag :one
INSERT INTO tag (name, repository_id, manifest_id, lifetime_start_ms, tag_kind_id, hidden)
VALUES (?, ?, ?, ?, ?, 1)
ON CONFLICT (repository_id, name, lifetime_end_ms) DO UPDATE SET manifest_id = excluded.manifest_id
RETURNING id
`

type InsertHiddenTagParams struct {
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
}

func (q *Queries) InsertHiddenTag(ctx context.Context, arg InsertHiddenTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertHiddenTag,
		arg.Name,
		arg.RepositoryID,
		arg.ManifestID,
		arg.LifetimeStartMs,
		arg.TagKindID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTemporaryTag = `-- name: InsertTemporaryTag :one
INSERT INTO tag (name, repository_id, manifest_id, lifetime_start_ms, lifetime_end_ms, tag_kind_id, hidden)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (repository_id, name, lifetime_end_ms) DO UPDATE SET manifest_id = excluded.manifest_id
RETURNING id
`

type InsertTemporaryTagParams struct {
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	LifetimeEndMs   sql.NullInt64 `json:"lifetime_end_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
	Hidden          bool          `json:"hidden"`
}

// Inserts a temporary tag on child manifest insertion guarding them from the GC process.
// If there is no guard, GC will remove them causing multiarch images to fail push.
func (q *Queries) InsertTemporaryTag(ctx context.Context, arg InsertTemporaryTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTemporaryTag,
		arg.Name,
		arg.RepositoryID,
		arg.ManifestID,
		arg.LifetimeStartMs,
		arg.LifetimeEndMs,
		arg.TagKindID,
		arg.Hidden,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const tagLifetimeEndExists = `-- name: TagLifetimeEndExists :one
SELECT EXISTS(
    SELECT 1
    FROM tag
    WHERE repository_id = ? AND name = ? AND lifetime_end_ms = ?
)
`

type TagLifetimeEndExistsParams struct {
	RepositoryID  int64         `json:"repository_id"`
	Name          string        `json:"name"`
	LifetimeEndMs sql.NullInt64 `json:"lifetime_end_ms"`
}

func (q *Queries) TagLifetimeEndExists(ctx context.Context, arg TagLifetimeEndExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, tagLifetimeEndExists, arg.RepositoryID, arg.Name, arg.LifetimeEndMs)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tag (name, repository_id, manifest_id, lifetime_start_ms, tag_kind_id)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (repository_id, name, lifetime_end_ms) DO UPDATE SET manifest_id = excluded.manifest_id
RETURNING id
`

type UpsertTagParams struct {
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
}

// KNOWN LIMITATION: ON CONFLICT uses lifetime_end_ms which is nullable.
// NULL != NULL in SQL, so active tags (lifetime_end_ms IS NULL) never conflict.
// This inserts duplicates instead of updating. Proper fix requires a partial
// unique index: CREATE UNIQUE INDEX ON tag (repository_id, name) WHERE lifetime_end_ms IS NULL.
// Until then, callers should expire the old tag before inserting a new one.
func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTag,
		arg.Name,
		arg.RepositoryID,
		arg.ManifestID,
		arg.LifetimeStartMs,
		arg.TagKindID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
