// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package daldb

import (
	"context"
	"database/sql"
)

const deleteTagsByManifest = `-- name: DeleteTagsByManifest :exec
DELETE FROM tag WHERE manifest_id = ?
`

func (q *Queries) DeleteTagsByManifest(ctx context.Context, manifestID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteTagsByManifest, manifestID)
	return err
}

const expireTagByID = `-- name: ExpireTagByID :execresult
UPDATE tag SET lifetime_end_ms = ?
WHERE id = ? AND lifetime_end_ms IS NULL
`

type ExpireTagByIDParams struct {
	LifetimeEndMs sql.NullInt64 `json:"lifetime_end_ms"`
	ID            int64         `json:"id"`
}

func (q *Queries) ExpireTagByID(ctx context.Context, arg ExpireTagByIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, expireTagByID, arg.LifetimeEndMs, arg.ID)
}

const getActiveTag = `-- name: GetActiveTag :one
SELECT id, manifest_id, lifetime_start_ms
FROM tag
WHERE repository_id = ? AND name = ? AND lifetime_end_ms IS NULL
ORDER BY id DESC
LIMIT 1
`

type GetActiveTagParams struct {
	RepositoryID int64  `json:"repository_id"`
	Name         string `json:"name"`
}

type GetActiveTagRow struct {
	ID              int64         `json:"id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
}

// Tag IDs preserve insertion order even when the wall clock moves backward.
func (q *Queries) GetActiveTag(ctx context.Context, arg GetActiveTagParams) (GetActiveTagRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveTag, arg.RepositoryID, arg.Name)
	var i GetActiveTagRow
	err := row.Scan(&i.ID, &i.ManifestID, &i.LifetimeStartMs)
	return i, err
}

const getLatestTagInterval = `-- name: GetLatestTagInterval :one
SELECT lifetime_start_ms, lifetime_end_ms
FROM tag
WHERE repository_id = ? AND name = ?
ORDER BY id DESC
LIMIT 1
`

type GetLatestTagIntervalParams struct {
	RepositoryID int64  `json:"repository_id"`
	Name         string `json:"name"`
}

type GetLatestTagIntervalRow struct {
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	LifetimeEndMs   sql.NullInt64 `json:"lifetime_end_ms"`
}

// Tag IDs preserve insertion order even when the wall clock moves backward.
func (q *Queries) GetLatestTagInterval(ctx context.Context, arg GetLatestTagIntervalParams) (GetLatestTagIntervalRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestTagInterval, arg.RepositoryID, arg.Name)
	var i GetLatestTagIntervalRow
	err := row.Scan(&i.LifetimeStartMs, &i.LifetimeEndMs)
	return i, err
}

const getLiveTagDigest = `-- name: GetLiveTagDigest :one
WITH latest_tag AS (
  SELECT t.manifest_id, t.lifetime_start_ms, t.lifetime_end_ms
  FROM tag t
  WHERE t.repository_id = ? AND t.name = ?
  ORDER BY t.id DESC
  LIMIT 1
)
SELECT m.digest
FROM latest_tag t
JOIN manifest m ON t.manifest_id = m.id
WHERE t.lifetime_end_ms IS NULL
   OR (t.lifetime_start_ms <= ? AND t.lifetime_end_ms > ?)
`

type GetLiveTagDigestParams struct {
	RepositoryID    int64         `json:"repository_id"`
	Name            string        `json:"name"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	LifetimeEndMs   sql.NullInt64 `json:"lifetime_end_ms"`
}

func (q *Queries) GetLiveTagDigest(ctx context.Context, arg GetLiveTagDigestParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getLiveTagDigest,
		arg.RepositoryID,
		arg.Name,
		arg.LifetimeStartMs,
		arg.LifetimeEndMs,
	)
	var digest string
	err := row.Scan(&digest)
	return digest, err
}

const getTagsByRepository = `-- name: GetTagsByRepository :many
WITH ranked_tags AS (
  SELECT name, lifetime_start_ms, lifetime_end_ms,
         row_number() OVER (
           PARTITION BY repository_id, name
           ORDER BY id DESC
         ) AS row_num
  FROM tag
  WHERE repository_id = ? AND hidden = 0
)
SELECT name
FROM ranked_tags
WHERE row_num = 1
  AND (lifetime_end_ms IS NULL OR (lifetime_start_ms <= ? AND lifetime_end_ms > ?))
ORDER BY name
`

type GetTagsByRepositoryParams struct {
	RepositoryID    int64         `json:"repository_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	LifetimeEndMs   sql.NullInt64 `json:"lifetime_end_ms"`
}

func (q *Queries) GetTagsByRepository(ctx context.Context, arg GetTagsByRepositoryParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByRepository, arg.RepositoryID, arg.LifetimeStartMs, arg.LifetimeEndMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertHiddenTag = `-- name: InsertHiddenTag :one
INSERT INTO tag (name, repository_id, manifest_id, lifetime_start_ms, tag_kind_id, hidden)
VALUES (?, ?, ?, ?, ?, 1)
ON CONFLICT (repository_id, name) WHERE lifetime_end_ms IS NULL
DO UPDATE SET manifest_id = excluded.manifest_id
RETURNING id
`

type InsertHiddenTagParams struct {
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
}

func (q *Queries) InsertHiddenTag(ctx context.Context, arg InsertHiddenTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertHiddenTag,
		arg.Name,
		arg.RepositoryID,
		arg.ManifestID,
		arg.LifetimeStartMs,
		arg.TagKindID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tag (name, repository_id, manifest_id, lifetime_start_ms, tag_kind_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertTagParams struct {
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTag,
		arg.Name,
		arg.RepositoryID,
		arg.ManifestID,
		arg.LifetimeStartMs,
		arg.TagKindID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
