// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package daldb

import (
	"context"
	"database/sql"
)

const getTagsByRepository = `-- name: GetTagsByRepository :many
SELECT id, name, repository_id, manifest_id, lifetime_start_ms, lifetime_end_ms, tag_kind_id
FROM tag WHERE repository_id = ? AND lifetime_end_ms IS NULL
`

type GetTagsByRepositoryRow struct {
	ID              int64         `json:"id"`
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	LifetimeEndMs   sql.NullInt64 `json:"lifetime_end_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
}

func (q *Queries) GetTagsByRepository(ctx context.Context, repositoryID int64) ([]GetTagsByRepositoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getTagsByRepository, repositoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTagsByRepositoryRow{}
	for rows.Next() {
		var i GetTagsByRepositoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RepositoryID,
			&i.ManifestID,
			&i.LifetimeStartMs,
			&i.LifetimeEndMs,
			&i.TagKindID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTag = `-- name: UpsertTag :one
INSERT INTO tag (name, repository_id, manifest_id, lifetime_start_ms, tag_kind_id)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT (repository_id, name, lifetime_end_ms) DO UPDATE SET manifest_id = excluded.manifest_id
RETURNING id
`

type UpsertTagParams struct {
	Name            string        `json:"name"`
	RepositoryID    int64         `json:"repository_id"`
	ManifestID      sql.NullInt64 `json:"manifest_id"`
	LifetimeStartMs int64         `json:"lifetime_start_ms"`
	TagKindID       int64         `json:"tag_kind_id"`
}

func (q *Queries) UpsertTag(ctx context.Context, arg UpsertTagParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertTag,
		arg.Name,
		arg.RepositoryID,
		arg.ManifestID,
		arg.LifetimeStartMs,
		arg.TagKindID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
