// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package daldb

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user (uuid, username, password_hash, email, verified_email,
  organization, robot, enabled, removed_tag_expiration_s,
  invalid_login_attempts, creation_date)
VALUES (?, ?, ?, ?, 1, 0, 0, 1, 1209600, 0, datetime('now'))
RETURNING id
`

type CreateUserParams struct {
	Uuid         sql.NullString `json:"uuid"`
	Username     string         `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Email        string         `json:"email"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Uuid,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, username, password_hash, email, enabled
FROM user WHERE username = ? AND organization = 0 AND robot = 0
`

type GetUserByUsernameRow struct {
	ID           int64          `json:"id"`
	Uuid         sql.NullString `json:"uuid"`
	Username     string         `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Email        string         `json:"email"`
	Enabled      bool           `json:"enabled"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Enabled,
	)
	return i, err
}
