// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package daldb

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM "user" WHERE organization = 0 AND robot = 0
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO "user" (uuid, username, password_hash, email, verified,
  organization, robot, invoice_email, invalid_login_attempts,
  last_invalid_login, removed_tag_expiration_s, enabled, creation_date)
VALUES (?, ?, ?, ?, 1, 0, 0, 0, 0, datetime('now'), 1209600, 1, datetime('now'))
RETURNING id
`

type CreateAdminUserParams struct {
	Uuid         sql.NullString `json:"uuid"`
	Username     string         `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Email        string         `json:"email"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser,
		arg.Uuid,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ensureUser = `-- name: EnsureUser :one
INSERT INTO "user" (username, email, verified, organization, robot,
  invoice_email, invalid_login_attempts, last_invalid_login,
  removed_tag_expiration_s, enabled)
VALUES (?1, ?1 || '@namespace.local', 1, 0, 0, 0, 0, datetime('now'), 1209600, 1)
ON CONFLICT (username) DO UPDATE SET username = excluded.username
RETURNING id
`

// Creates a synthetic user row for namespace resolution. Mirror-registry
// namespaces map 1:1 to user rows; these are not real login accounts.
func (q *Queries) EnsureUser(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, ensureUser, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, username, password_hash, email, enabled
FROM "user"
WHERE username = ? AND organization = 0 AND robot = 0
`

type GetUserByUsernameRow struct {
	ID           int64          `json:"id"`
	Uuid         sql.NullString `json:"uuid"`
	Username     string         `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Email        string         `json:"email"`
	Enabled      bool           `json:"enabled"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Enabled,
	)
	return i, err
}
