// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package daldb

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM "user" WHERE organization = 0 AND robot = 0
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO "user" (uuid, username, password_hash, email, verified,
  organization, robot, invoice_email, invalid_login_attempts,
  last_invalid_login, removed_tag_expiration_s, enabled, creation_date)
VALUES (?, ?, ?, ?, 1, 0, 0, 0, 0, datetime('now'), 1209600, 1, datetime('now'))
RETURNING id
`

type CreateAdminUserParams struct {
	Uuid         sql.NullString `json:"uuid"`
	Username     string         `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Email        string         `json:"email"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAdminUser,
		arg.Uuid,
		arg.Username,
		arg.PasswordHash,
		arg.Email,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const ensureUser = `-- name: EnsureUser :one
INSERT INTO "user" (username, email, verified, organization, robot,
  invoice_email, invalid_login_attempts, last_invalid_login,
  removed_tag_expiration_s, enabled)
VALUES (?1, ?1 || '@namespace.local', 1, 0, 0, 0, 0, datetime('now'), 1209600, 1)
ON CONFLICT (username) DO UPDATE SET username = excluded.username
RETURNING id
`

// Creates a synthetic user row for namespace resolution. Mirror-registry
// namespaces map 1:1 to user rows; these are not real login accounts.
func (q *Queries) EnsureUser(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRowContext(ctx, ensureUser, username)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getNamespaceUserByUsername = `-- name: GetNamespaceUserByUsername :one
SELECT id, username, enabled
FROM "user"
WHERE username = ?1
`

type GetNamespaceUserByUsernameRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Enabled  bool   `json:"enabled"`
}

func (q *Queries) GetNamespaceUserByUsername(ctx context.Context, username string) (GetNamespaceUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceUserByUsername, username)
	var i GetNamespaceUserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.Enabled)
	return i, err
}

const getRobotByUsername = `-- name: GetRobotByUsername :one
SELECT id, uuid, username, email, enabled, last_accessed
FROM "user"
WHERE username = ?1 AND robot = 1
`

type GetRobotByUsernameRow struct {
	ID           int64          `json:"id"`
	Uuid         sql.NullString `json:"uuid"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	Enabled      bool           `json:"enabled"`
	LastAccessed sql.NullTime   `json:"last_accessed"`
}

func (q *Queries) GetRobotByUsername(ctx context.Context, username string) (GetRobotByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getRobotByUsername, username)
	var i GetRobotByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.Email,
		&i.Enabled,
		&i.LastAccessed,
	)
	return i, err
}

const getRobotTokenByRobotID = `-- name: GetRobotTokenByRobotID :one
SELECT token
FROM robotaccounttoken
WHERE robot_account_id = ?1
`

func (q *Queries) GetRobotTokenByRobotID(ctx context.Context, robotID int64) (string, error) {
	row := q.db.QueryRowContext(ctx, getRobotTokenByRobotID, robotID)
	var token string
	err := row.Scan(&token)
	return token, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, uuid, username, password_hash, email, enabled
FROM "user"
WHERE username = ? AND organization = 0 AND robot = 0
`

type GetUserByUsernameRow struct {
	ID           int64          `json:"id"`
	Uuid         sql.NullString `json:"uuid"`
	Username     string         `json:"username"`
	PasswordHash sql.NullString `json:"password_hash"`
	Email        string         `json:"email"`
	Enabled      bool           `json:"enabled"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Username,
		&i.PasswordHash,
		&i.Email,
		&i.Enabled,
	)
	return i, err
}

const updateUserLastAccessedIfOlder = `-- name: UpdateUserLastAccessedIfOlder :exec
UPDATE "user"
SET last_accessed = datetime('now')
WHERE id = ?1
  AND (
    last_accessed IS NULL
    OR ?2 <= 0
    OR last_accessed <= datetime('now', '-' || ?2 || ' seconds')
  )
`

type UpdateUserLastAccessedIfOlderParams struct {
	UserID           int64       `json:"user_id"`
	ThresholdSeconds interface{} `json:"threshold_seconds"`
}

func (q *Queries) UpdateUserLastAccessedIfOlder(ctx context.Context, arg UpdateUserLastAccessedIfOlderParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastAccessedIfOlder, arg.UserID, arg.ThresholdSeconds)
	return err
}
