#! /bin/bash

echo 'Starting Blob upload cleanup worker'

QUAYPATH=${QUAYPATH:-"."}

cd ${QUAYDIR:-"/"}
PYTHONPATH=$QUAYPATH venv/bin/python -m workers.blobuploadcleanupworker.blobuploadcleanupworker 2>&1

echo 'Blob upload cleanup exited'