from ldap.controls.simple import *
from ldap.controls.libldap import *
from typing import Any, Optional

KNOWN_RESPONSE_CONTROLS: Any

class RequestControl:
    controlType: Any = ...
    criticality: Any = ...
    encodedControlValue: Any = ...
    def __init__(self, controlType: Optional[Any] = ..., criticality: bool = ..., encodedControlValue: Optional[Any] = ...) -> None: ...
    def encodeControlValue(self): ...

class ResponseControl:
    controlType: Any = ...
    criticality: Any = ...
    def __init__(self, controlType: Optional[Any] = ..., criticality: bool = ...) -> None: ...
    encodedControlValue: Any = ...
    def decodeControlValue(self, encodedControlValue: Any) -> None: ...

class LDAPControl(RequestControl, ResponseControl):
    controlType: Any = ...
    criticality: Any = ...
    controlValue: Any = ...
    encodedControlValue: Any = ...
    def __init__(self, controlType: Optional[Any] = ..., criticality: bool = ..., controlValue: Optional[Any] = ..., encodedControlValue: Optional[Any] = ...) -> None: ...

def RequestControlTuples(ldapControls: Any): ...
def DecodeControlTuples(ldapControlTuples: Any, knownLDAPControls: Optional[Any] = ...): ...

# Names in __all__ with no definition:
#   AssertionControl
#   BooleanControl
#   ManageDSAITControl
#   MatchedValuesControl
#   RelaxRulesControl
#   SimplePagedResultsControl
#   ValueLessRequestControl
