{
 "title": "quayio-usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "log_group",
    "label": "Log Group",
    "query": "osd-us-east-1/quay/app,osd-us-east-2/quay/app"
   }
  ]
 },
 "panels": [
  {
   "title": "Top namespaces",
   "type": "bargauge",
   "description": "Top namespaces associated with requests to v2 endpoint based on nginx logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "filter @message like /nginx\\[\\d+\\]/\n| parse @message '* * *[*]: * (*) * * [*] \"* * *\" * *' as datetime, podname, pname, pid, ip1, ip2, user1, user2, datetime2, http_verb, http_uri, http_version, statuscode, rest\n| parse http_uri /(?<namespace>(?<=^\\/v2\\/)([^auth][a-zA-z0-9-_]+)(?=\\/?))/\n| filter not isempty(namespace)\n| stats count(*) as req_count by namespace\n| sort by req_count desc\n| limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "namespace" ]
    }
   ]
  },
  {
   "title": "Top namespaces",
   "type": "piechart",
   "description": "Top namespaces associated with requests to v2 endpoint based on nginx logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "filter @message like /nginx\\[\\d+\\]/\n| parse @message '* * *[*]: * (*) * * [*] \"* * *\" * *' as datetime, podname, pname, pid, ip1, ip2, user1, user2, datetime2, http_verb, http_uri, http_version, statuscode, rest\n| parse http_uri /(?<namespace>(?<=^\\/v2\\/)([^auth][a-zA-z0-9-_]+)(?=\\/?))/\n| filter not isempty(namespace)\n| stats count(*) as req_count by namespace\n| sort by req_count desc\n| limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "namespace" ]
    }
   ]
  },
  {
   "title": "Top client IPs",
   "type": "table",
   "description": "Top client IP addresses associated with requests based on nginx logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expression": "filter @message like /nginx\\[\\d+\\]/\n| parse @message '* * *[*]: * (*) * * [*] \"* * *\" * *' as datetime, podname, pname, pid, ip1, ip2, user1, user2, datetime2, http_verb, http_uri, http_version, statuscode, rest\n| filter http_verb not in ['<exclude_ineffective_http_method>', 'HEAD']\n| stats count(*) as ip_count group by ip1\n| sort by ip_count desc\n| limit 20",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "ip1" ]
    }
   ]
  },
  {
   "title": "Top quay.io accounts",
   "type": "bargauge",
   "description": "Top requests by quay username based on nginx logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expression": "filter @message like /nginx\\[\\d+\\]/\n| parse @message '* * *[*]: * (*) * * [*] \"* * *\" * *' as datetime, podname, pname, pid, ip1, ip2, user1, username, datetime2, http_verb, http_uri, http_version, statuscode, rest\n| filter http_verb not in ['HEAD']\n| filter not isempty(username) and username != \"-\"\n| stats count(*) as req_count by username\n| sort by req_count desc\n| limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "username" ]
    }
   ]
  },
  {
   "title": "Image Pulls Total",
   "type": "timeseries",
   "description": "Counter for number of images pulled",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(quay_registry_image_pulls_total{protocol=\"v2\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Repos",
   "type": "barchart",
   "description": "Top repos requested based on nginx logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expression": "filter @message like /nginx\\[\\d+\\]/\n| parse @message '* * *[*]: * (*) * * [*] \"* * *\" * *' as datetime, podname, pname, pid, ip1, ip2, user1, user2, datetime2, http_verb, http_uri, http_version, statuscode, rest\n| filter http_verb not in ['HEAD']\n| parse http_uri \"/v2/*/manifests/\" as repo\n| filter not isempty(repo)\n| stats count(*) as req_count by repo\n| sort by req_count desc\n| limit 10",
     "logGroups": [
      { "arn": "$log_group", "name": "$log_group" }
     ],
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Logs",
     "region": "default",
     "statistic": "Average",
     "statsGroups": [ "repo" ]
    }
   ]
  }
 ]
}