{
 "title": "Quay SLO",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "rate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "catchpoint_datasource", "query": "prometheus" },
   { "name": "cloudwatch_datasource", "query": "cloudwatch" }
  ]
 },
 "panels": [
  {
   "title": "Pull Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "99.9", "legendFormat": "pull target" },
    {
     "expr": "100 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n)",
     "legendFormat": "pull availability"
    },
    {
     "expr": "100 * (\n  (100 - 99.9) - 100 * (\n    (\n      sum(increase(catchpoint_check_failures_total{probe=\"quayio-pull-monitor-v2\"}[$rate])) \n      / sum(increase(catchpoint_checks_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))\n    )\n  )\n)\n/\n(100 - 99.9)",
     "legendFormat": "error budget left"
    }
   ]
  },
  {
   "title": "Push Operations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "99.5", "legendFormat": "push target" },
    {
     "expr": "100 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n)",
     "legendFormat": "push availability"
    },
    {
     "expr": "100 * (\n  (100 - 99.5) - 100 * (\n    (\n      sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-monitor-v2\"}[$rate])) \n      / sum(increase(catchpoint_checks_total{probe=\"quayio-push-monitor-v2\"}[$rate]))\n    )\n  )\n)\n/\n(100 - 99.5)",
     "legendFormat": "error budget left"
    }
   ]
  },
  {
   "title": "repository endpoint (v1 Quay API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET repository"
    },
    {
     "expr": "(\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\", status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",method=\"GET\"}[$rate]))\n) - 0.995",
     "legendFormat": "error budget "
    }
   ]
  },
  {
   "title": "security endpoint (v1 Quay API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET security"
    },
    {
     "expr": "(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n    /\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",method=\"GET\"}[$rate]))\n)\n- 0.995",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "GET blob success rate (v2 Registry API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.999\n", "legendFormat": "target" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.download_blob\", status!~\"5[0-9][0-9]\", method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.download_blob\", method=\"GET\"}[$rate]))",
     "legendFormat": "GET blob"
    },
    {
     "expr": "(\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.download_blob\", status!~\"5[0-9][0-9]\", method=\"GET\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.download_blob\", method=\"GET\"}[$rate]))\n) - 0.999",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "upload blob success rate (v2 Registry API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target" },
    {
     "expr": "(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.start_blob_upload\", method=\"POST\", status!~\"5[0-9][0-9]\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.monolithic_upload_or_last_chunk\", method=\"PUT\", status!~\"5[0-9][0-9]\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.upload_chunk\", method=\"PATCH\", status!~\"5[0-9][0-9]\"}[$rate]))\n)\n/\n(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.start_blob_upload\", method=\"POST\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.monolithic_upload_or_last_chunk\", method=\"PUT\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.upload_chunk\", method=\"PATCH\"}[$rate]))\n)",
     "legendFormat": "upload blob"
    },
    {
     "expr": "(    \n    (\n        sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.start_blob_upload\", method=\"POST\", status!~\"5[0-9][0-9]\"}[$rate]))\n        + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.monolithic_upload_or_last_chunk\", method=\"PUT\", status!~\"5[0-9][0-9]\"}[$rate]))\n        + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.upload_chunk\", method=\"PATCH\", status!~\"5[0-9][0-9]\"}[$rate]))\n    )\n    /\n    (\n        sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.start_blob_upload\", method=\"POST\"}[$rate]))\n        + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.monolithic_upload_or_last_chunk\", method=\"PUT\"}[$rate]))\n        + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.upload_chunk\", method=\"PATCH\"}[$rate]))\n    )\n) - 0.995",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "tags endpoint (v1 Quay API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET tags"
    },
    {
     "expr": "(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n    /\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",method=\"GET\"}[$rate]))\n)\n- 0.995",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "users endpoint (v1 Quay API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target availability" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",status!~\"5[0-9[0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",method=\"GET\"}[$rate]))",
     "legendFormat": "GET user"
    },
    {
     "expr": "(\n  \n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",status!~\"5[0-9[0-9]\",method=\"GET\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",method=\"GET\"}[$rate]))\n\n)\n-\n0.995",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "upload manifest success rate (v2 Registry API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target" },
    {
     "expr": "(\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_tagname\", status!~\"5[0-9][0-9]\"}[$rate]))\n  + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_digest\",status!~\"5[0-9][0-9]\"}[$rate]))\n)\n/ \n(\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_tagname\"}[$rate]))\n   + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_digest\"}[$rate]))\n)",
     "legendFormat": "upload manifest"
    },
    {
     "expr": "(    \n    (\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_tagname\", status!~\"5[0-9][0-9]\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_digest\",status!~\"5[0-9][0-9]\"}[$rate]))\n    )\n    / \n    (\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_tagname\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_digest\"}[$rate]))\n    )\n) - 0.995",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "GET manifest success rate (v2 Registry API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.999\n", "legendFormat": "target" },
    {
     "expr": "(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_tagname\", status!~\"5[0-9][0-9]\"}[5m]))\n    +\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_digest\", status!~\"5[0-9][0-9]\"}[5m]))\n)\n/\n(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_digest\"}[5m]))\n    +\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_tagname\"}[5m]))\n)\n",
     "legendFormat": "GET manifest"
    },
    {
     "expr": "(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_tagname\", status!~\"5[0-9][0-9]\"}[5m]))\n    +\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_digest\", status!~\"5[0-9][0-9]\"}[5m]))\n)\n/\n(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_digest\"}[5m]))\n    +\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_tagname\"}[5m]))\n) - 0.999\n",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "GET auth success rate (v2 Registry API)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.999\n", "legendFormat": "target" },
    {
     "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.generate_registry_jwt\", method=\"GET\", status!~\"5[0-9][0-9]\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.generate_registry_jwt\", method=\"GET\"}[$rate]))",
     "legendFormat": "GET auth"
    },
    {
     "expr": "(  \n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.generate_registry_jwt\", method=\"GET\", status!~\"5[0-9][0-9]\"}[$rate]))\n  /\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.generate_registry_jwt\", method=\"GET\"}[$rate]))\n) - 0.999",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "Build Success",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "0.995", "legendFormat": "target" },
    {
     "expr": "sum(increase(quay_build_jobs_total{success=\"true\"}[$rate]))\n/\nsum(increase(quay_build_jobs_total[$rate]))",
     "legendFormat": "success %"
    },
    {
     "expr": "(\n  sum(increase(quay_build_jobs_total{success=\"true\"}[$rate]))\n  /\n  sum(increase(quay_build_jobs_total[$rate]))\n) - 0.995",
     "legendFormat": "error budget"
    }
   ]
  },
  {
   "title": "Average Time in Build Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(quay_build_queue_duration_seconds_sum[$rate]))\n/\nsum(increase(quay_build_queue_duration_seconds_count[$rate]))"
    }
   ]
  },
  {
   "title": "Push/Pull",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Push-Pull Monitor by Region",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-pull-monitor-v2-na\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-pull-monitor-v2-na\"}[$rate]))\n)\n",
       "legendFormat": "North America"
      },
      {
       "expr": "1 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-pull-monitor-v2-sa\"}[$rate]))\n    /\n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-pull-monitor-v2-sa\"}[$rate]))\n)",
       "legendFormat": "South America"
      },
      {
       "expr": "1 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-pull-monitor-v2-af\"}[$rate]))\n    /   \n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-pull-monitor-v2-af\"}[$rate]))\n)",
       "legendFormat": "Africa"
      },
      {
       "expr": "1 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-pull-monitor-v2-as\"}[$rate]))\n    /   \n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-pull-monitor-v2-as\"}[$rate]))\n)",
       "legendFormat": "Asia"
      },
      {
       "expr": "1 - (\n    sum(increase(catchpoint_check_failures_total{probe=\"quayio-push-pull-monitor-v2-oc\"}[$rate]))\n    /   \n    sum(increase(catchpoint_checks_total{probe=\"quayio-push-pull-monitor-v2-oc\"}[$rate]))\n)",
       "legendFormat": "Oceania"
      }
     ]
    },
    {
     "title": "Push Error Budget Burn Rate (WIP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "increase(catchpoint_check_failures_total{probe=\"quayio-push-monitor-v2\"}[$rate])",
       "legendFormat": "budget burn rate"
      },
      {
       "expr": "(100 - 99.5) * increase(catchpoint_checks_total{probe=\"quayio-push-monitor-v2\"}[$rate])",
       "legendFormat": "max budget"
      }
     ]
    },
    {
     "title": "Pull Error Budget Burn Rate (WIP)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(catchpoint_check_failures_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))",
       "legendFormat": "budget burn rate"
      },
      {
       "expr": "(100 - 99.9) * sum(increase(catchpoint_checks_total{probe=\"quayio-pull-monitor-v2\"}[$rate]))",
       "legendFormat": "max budget"
      }
     ]
    }
   ]
  },
  {
   "title": "v1 Quay API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "API v1 Availability",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.user\",method=\"GET\"}[$rate]))",
       "legendFormat": "GET api.user"
      },
      {
       "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repository\",method=\"GET\"}[$rate]))",
       "legendFormat": "GET api.repository"
      },
      {
       "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.listrepositorytags\",method=\"GET\"}[$rate]))",
       "legendFormat": "GET api.listrepositorytags"
      },
      {
       "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",status!~\"5[0-9][0-9]\",method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"api.repositorymanifestsecurity\",method=\"GET\"}[$rate]))",
       "legendFormat": "GET api.repositorymanifestsecurity"
      }
     ]
    },
    {
     "title": "HTTP response codes",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 2XX",
       "metricName": "HTTPCode_Target_2XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 3XX",
       "metricName": "HTTPCode_Target_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 4XX",
       "metricName": "HTTPCode_Target_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 5XX",
       "metricName": "HTTPCode_Target_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "HTTP response codes",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 2XX",
       "metricName": "HTTPCode_Target_2XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 3XX",
       "metricName": "HTTPCode_Target_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 4XX",
       "metricName": "HTTPCode_Target_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": {
        "LoadBalancer": "app/quayio-production-alb01/dd2a8a128b2029c6"
       },
       "label": "HTTP 5XX",
       "metricName": "HTTPCode_Target_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  {
   "title": "v2 Registry API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "v2 registry api",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_tagname\", status!~\"5[0-9][0-9]\", method=\"GET\"}[5m]))\n    +\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_digest\", status!~\"5[0-9][0-9]\", method=\"GET\"}[5m]))\n)\n/\n(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_digest\", method=\"GET\"}[5m]))\n    +\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.fetch_manifest_by_tagname\", method=\"GET\"}[5m]))\n)",
       "legendFormat": "GET manifest success rate"
      },
      {
       "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.generate_registry_jwt\", method=\"GET\", status!~\"5[0-9][0-9]\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.generate_registry_jwt\", method=\"GET\"}[$rate]))",
       "legendFormat": "auth success rate"
      },
      {
       "expr": "sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.download_blob\", status!~\"5[0-9][0-9]\", method=\"GET\"}[$rate]))\n/\nsum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.download_blob\", method=\"GET\"}[$rate]))",
       "legendFormat": "GET blob success rate"
      },
      {
       "expr": "(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.start_blob_upload\", method=\"POST\", status!~\"5[0-9][0-9]\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.monolithic_upload_or_last_chunk\", method=\"PUT\", status!~\"5[0-9][0-9]\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.upload_chunk\", method=\"PATCH\", status!~\"5[0-9][0-9]\"}[$rate]))\n)\n/\n(\n    sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.start_blob_upload\", method=\"POST\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.monolithic_upload_or_last_chunk\", method=\"PUT\"}[$rate]))\n    + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.upload_chunk\", method=\"PATCH\"}[$rate]))\n)",
       "legendFormat": "upload blob success rate"
      },
      {
       "expr": "(\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_tagname\", status!~\"5[0-9][0-9]\"}[$rate]))\n  + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_digest\",status!~\"5[0-9][0-9]\"}[$rate]))\n)\n/ \n(\n  sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_tagname\"}[$rate]))\n   + sum(increase(aggregation:quay_request_duration_seconds_count:rate1m:sum{route=\"v2.write_manifest_by_digest\"}[$rate]))\n)\n",
       "legendFormat": "upload manifest success rate"
      }
     ]
    },
    {
     "title": "v2 response codes",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 6, "x": 9, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(aggregation:quay_request_duration_seconds_count:rate1m:sum{route =~ \"v2.*\", status =~ \"2[0-9][0-9]\"}[$rate]))",
       "legendFormat": "2XX"
      },
      {
       "expr": "sum(rate(aggregation:quay_request_duration_seconds_count:rate1m:sum{route =~ \"v2.*\", status =~ \"3[0-9][0-9]\"}[$rate]))",
       "legendFormat": "3XX"
      },
      {
       "expr": "sum(rate(aggregation:quay_request_duration_seconds_count:rate1m:sum{route =~ \"v2.*\", status =~ \"4[0-9][0-9]\"}[$rate]))",
       "legendFormat": "4XX"
      },
      {
       "expr": "sum(rate(aggregation:quay_request_duration_seconds_count:rate1m:sum{route =~ \"v2.*\", status =~ \"5[0-9][0-9]\"}[$rate]))",
       "legendFormat": "5XX"
      }
     ]
    }
   ]
  },
  {
   "title": "Builds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Build Time",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(\n    sum(\n        increase(quay_build_queue_duration_seconds_sum[$rate])\n    )\n    /\n    sum(\n        increase(quay_build_queue_duration_seconds_count[$rate])\n    )\n) + (\n    sum(\n        increase(quay_build_duration_seconds_sum[$rate])\n    )\n    /\n    sum(\n        increase(quay_build_duration_seconds_count[$rate])\n    )\n)"
      }
     ]
    },
    {
     "title": "Time in Build Queue Distribution",
     "type": "histogram",
     "description": "Distribution of time spent in the build queue over specified `rate`",
     "gridPos": { "h": 8, "w": 7, "x": 5, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(rate(quay_build_queue_duration_seconds_sum[$rate])) / sum(rate(quay_build_queue_duration_seconds_count[$rate]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Build Queue Duration",
     "type": "heatmap",
     "description": "Heatmap of time spent in queue for build jobs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "sum(increase(quay_build_queue_duration_seconds_bucket{schedule_success=\"True\"}[$rate])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Clair",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Time For Scan Results",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(quay_secscan_result_duration_seconds_sum[$rate]))\n/\nsum(increase(quay_secscan_result_duration_seconds_count[$rate]))"
      }
     ]
    },
    {
     "title": "Scan Result Latency",
     "type": "heatmap",
     "description": "duration of time between pushing an image to quay and receiving scan results",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 21 },
     "targets": [
      {
       "expr": "sum(increase(quay_secscan_result_duration_seconds_bucket[$rate])) by (le)",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  }
 ]
}