name: 'Setup Quay Local Dev'
description: 'Set up Quay container registry for CI testing using docker-compose'
author: 'Project Quay'

branding:
  icon: 'box'
  color: 'red'

inputs:
  extra-config-file:
    description: 'Path to extra config to append to config.yaml'
    required: false
    default: ''

  extra-config:
    description: 'Inline YAML config to merge into config.yaml'
    required: false
    default: ''

  health-check-timeout:
    description: 'Health check timeout in seconds'
    required: false
    default: '120'

  with-clair:
    description: 'Start Clair security scanner'
    required: false
    default: 'false'

  with-repomirror:
    description: 'Start Quay repository mirroring worker'
    required: false
    default: 'false'

  with-ldap:
    description: 'Start LDAP server and configure Quay for LDAP auth'
    required: false
    default: 'false'

  with-mailpit:
    description: 'Start Mailpit email testing server'
    required: false
    default: 'true'

outputs:
  quay-url:
    description: 'URL where Quay is accessible'
    value: ${{ steps.healthcheck.outputs.quay-url }}

  container-name:
    description: 'Name of the Quay container'
    value: 'quay-quay'

  react-dev-url:
    description: 'URL where React dev server is accessible'
    value: ${{ steps.react-healthcheck.outputs.react-dev-url }}

runs:
  using: 'composite'
  steps:
    - name: Start LDAP server
      if: inputs.with-ldap == 'true'
      shell: bash
      run: |
        docker compose up -d ldap
        echo "Waiting for LDAP to be ready..."
        # Poll until LDAP responds and base DN exists (init script completed)
        timeout=60
        while [ $timeout -gt 0 ]; do
          if docker exec quay-ldap ldapsearch -x -H ldap://localhost:3389 \
              -D "cn=Directory Manager" -w admin \
              -b "dc=example,dc=org" -s base &>/dev/null; then
            echo "LDAP is ready!"
            break
          fi
          sleep 2
          timeout=$((timeout - 2))
        done
        if [ $timeout -le 0 ]; then
          echo "::error::LDAP failed to initialize within 60 seconds"
          docker logs quay-ldap
          exit 1
        fi

    - name: Configure LDAP authentication
      if: inputs.with-ldap == 'true'
      shell: bash
      run: |
        BASE_CONFIG="local-dev/stack/config.yaml"
        LDAP_CONFIG="local-dev/ldap/ldap-config.yaml"

        pip install pyyaml -q
        python3 ${{ github.action_path }}/merge-yaml.py \
          "${BASE_CONFIG}" "${LDAP_CONFIG}" > "${BASE_CONFIG}.tmp"
        mv "${BASE_CONFIG}.tmp" "${BASE_CONFIG}"
        echo "LDAP configuration merged"

    - name: Merge extra config file
      if: inputs.extra-config-file != ''
      shell: bash
      run: |
        EXTRA_CONFIG="${{ inputs.extra-config-file }}"
        BASE_CONFIG="local-dev/stack/config.yaml"

        if [ ! -f "${EXTRA_CONFIG}" ]; then
          echo "::error::extra-config-file '${EXTRA_CONFIG}' not found"
          exit 1
        fi

        echo "Merging ${EXTRA_CONFIG} into ${BASE_CONFIG}..."
        pip install pyyaml -q
        python3 ${{ github.action_path }}/merge-yaml.py \
          "${BASE_CONFIG}" "${EXTRA_CONFIG}" > "${BASE_CONFIG}.tmp"
        mv "${BASE_CONFIG}.tmp" "${BASE_CONFIG}"
        echo "Config merged successfully"

    - name: Merge inline extra config
      if: inputs.extra-config != ''
      shell: bash
      env:
        EXTRA_CONFIG_CONTENT: ${{ inputs.extra-config }}
      run: |
        set -euo pipefail
        BASE_CONFIG="local-dev/stack/config.yaml"
        INLINE_CONFIG=$(mktemp --suffix=.yaml)

        printf '%s\n' "${EXTRA_CONFIG_CONTENT}" > "${INLINE_CONFIG}"

        echo "Merging inline config into ${BASE_CONFIG}..."
        pip install pyyaml -q
        python3 ${{ github.action_path }}/merge-yaml.py \
          "${BASE_CONFIG}" "${INLINE_CONFIG}" > "${BASE_CONFIG}.tmp"
        mv "${BASE_CONFIG}.tmp" "${BASE_CONFIG}"
        rm -f "${INLINE_CONFIG}"
        echo "Inline config merged successfully"

    - name: Start Quay local dev environment
      shell: bash
      run: |
        make local-dev-up

    - name: Wait for Quay to be ready
      id: healthcheck
      shell: bash
      run: |
        echo "Waiting for Quay to be ready..."

        TIMEOUT=${{ inputs.health-check-timeout }}
        RETRY_DELAY=2
        MAX_RETRIES=$((TIMEOUT / RETRY_DELAY))

        if curl -sf --retry ${MAX_RETRIES} --retry-delay ${RETRY_DELAY} --retry-all-errors \
            http://localhost:8080/health/instance > /dev/null 2>&1; then
          echo "Quay is ready!"
          echo "quay-url=http://localhost:8080" >> $GITHUB_OUTPUT
        else
          echo "Quay failed to become ready within ${TIMEOUT} seconds"
          docker logs quay-quay 2>&1 | tail -100
          exit 1
        fi

    - name: Wait for React dev server to be ready
      id: react-healthcheck
      shell: bash
      run: |
        echo "Waiting for React dev server (local-dev-react) to be ready..."

        TIMEOUT=${{ inputs.health-check-timeout }}
        RETRY_DELAY=2
        MAX_RETRIES=$((TIMEOUT / RETRY_DELAY))

        if curl -sf --retry ${MAX_RETRIES} --retry-delay ${RETRY_DELAY} --retry-all-errors \
            http://localhost:9000 > /dev/null 2>&1; then
          echo "React dev server is ready!"
          echo "react-dev-url=http://localhost:9000" >> $GITHUB_OUTPUT
        else
          echo "React dev server failed to become ready within ${TIMEOUT} seconds"
          docker compose logs local-dev-react 2>&1 | tail -100
          exit 1
        fi

    - name: Start Clair
      if: inputs.with-clair == 'true'
      shell: bash
      run: |
        docker compose up -d clair-db
        docker exec clair-db bash -c 'while ! pg_isready; do echo "waiting for clair postgres"; sleep 2; done'
        DOCKER_USER="1001:0" docker compose up -d clair
        echo "Waiting for Clair to initialize..."
        sleep 30

    - name: Start Repomirror
      if: inputs.with-repomirror == 'true'
      shell: bash
      run: |
        DOCKER_USER="1001:0" docker compose up -d repomirror
        echo "Repomirror worker started"

    - name: Start Mailpit
      if: inputs.with-mailpit == 'true'
      shell: bash
      run: |
        docker compose up -d mailpit
        echo "Mailpit email server started (SMTP: localhost:1025, Web UI: localhost:8025)"
