#! /bin/bash

QUAYPATH=${QUAYPATH:-"."}
cd ${QUAYDIR:-"/"}
PYTHONPATH=$QUAYPATH
QUAYCONF=${QUAYCONF:-"$QUAYPATH/conf"}

if [ -f $QUAYCONF/jwtproxy_conf.yaml ];
then
  echo 'Starting jwtproxy'
  /usr/local/bin/jwtproxy --config $QUAYCONF/jwtproxy_conf.yaml
  rm /tmp/jwtproxy_secscan.sock
  echo 'Jwtproxy exited'
else
  sleep 1
fi
