{
 "title": "GC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tables",
    "label": "table",
    "query": {
     "query": "label_values(quay_gc_table_rows_deleted_total, table)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "GC metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rows deleted",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "Workers",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quay_gc_iterations_total{process_name=\"gcworker.py\"})",
     "legendFormat": "gcworker iterations"
    },
    {
     "expr": "sum(quay_gc_repos_purged_total{process_name=~\"repositorygcworker.py|namespacegcworker.py\"})",
     "legendFormat": "repos purged"
    },
    {
     "expr": "sum(quay_gc_namespaces_purged_total{process_name=\"namespacegcworker.py\"})",
     "legendFormat": "namespaces purged"
    }
   ]
  },
  {
   "title": "Rows deleted per second [15m]",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\"}[15m]))",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(rate(quay_gc_table_rows_deleted_total{process_name=~\"repositorygcworker.py\"}[15m]))",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(rate(quay_gc_table_rows_deleted_total{process_name=~\"namespacegcworker.py\"}[15m]))",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "Storage blobs deleted",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quay_gc_storage_blobs_deleted_total{process_name=~\"namespacegcworker.py|repositorygcworker.py|gcworker.py\"})",
     "legendFormat": "storage blobs deleted"
    }
   ]
  },
  {
   "title": "Namespace GC queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "max(quay_queue_items_locked{queue_name=\"namespacegc\"})",
     "legendFormat": "locked"
    },
    {
     "expr": "max(quay_queue_items_available{queue_name=\"namespacegc\"})",
     "legendFormat": "available"
    },
    {
     "expr": "max(quay_queue_items_available_unlocked{queue_name=\"namespacegc\"})",
     "legendFormat": "available unlocked"
    }
   ]
  },
  {
   "title": "Repository GC queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    {
     "expr": "max(quay_queue_items_locked{queue_name=\"repositorygc\"})",
     "legendFormat": "locked"
    },
    {
     "expr": "max(quay_queue_items_available{queue_name=\"repositorygc\"})",
     "legendFormat": "available"
    },
    {
     "expr": "max(quay_queue_items_available_unlocked{queue_name=\"repositorygc\"})",
     "legendFormat": "available unlocked"
    }
   ]
  },
  { "title": "Table rows deleted", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "repeat": "tables",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  },
  {
   "title": "$tables",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"gcworker.py\", table=\"$tables\"})",
     "legendFormat": "gcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"repositorygcworker.py\", table=\"$tables\"})",
     "legendFormat": "repositorygcworker"
    },
    {
     "expr": "sum(quay_gc_table_rows_deleted_total{process_name=\"namespacegcworker.py\", table=\"$tables\"})",
     "legendFormat": "namespacegcworker"
    }
   ]
  }
 ]
}