{
 "title": "Quay AWS Resources",
 "tags": [
  "quay",
  "aws",
  "prod"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "quay_db",
    "query": "label_values(aws_rds_cpuutilization_average, dbinstance_identifier)"
   },
   {
    "name": "apostille_db",
    "query": "label_values(aws_rds_cpuutilization_average, dbinstance_identifier)"
   },
   { "name": "distribution_id", "query": "label_values(distribution_id)" },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "cloud_watch_service", "query": "label_values(service)" },
   { "name": "cache_cluster_prefix", "query": "quayio" }
  ]
 },
 "panels": [
  {
   "title": "AWS/RDS (quay)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "[AWS/RDS] CPUUtilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_cpuutilization_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Database Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "none", "label": "Database Connections" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_database_connections_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Read/Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_read_iops_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "read"
      },
      {
       "expr": "max without(pod,instance) (aws_rds_write_iops_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Read/Write Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_read_latency_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "read"
      },
      {
       "expr": "max without(pod,instance) (aws_rds_write_latency_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Volume Burst Balance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_burst_balance_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "burst balance"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Free Storage Space",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"$quay_db\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Quay Monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pull/push time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (quay_monitor_monitor_pull_time_average)",
       "legendFormat": "pull"
      },
      {
       "expr": "max without(pod,instance) (quay_monitor_monitor_push_time_average)",
       "legendFormat": "push"
      }
     ]
    },
    {
     "title": "Success ratio",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (quay_monitor_monitor_success_average) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "AWS/ElastiCache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "[AWS/ElastiCache] CPUUtilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_cpuutilization_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] ReplicationLag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_replication_lag_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] CurrConnections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_curr_connections_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] NewConnections",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_new_connections_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] CacheHits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_cache_hits_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] CacheMisses",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_cache_misses_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] NetworkBytesIn",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_network_bytes_in_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    },
    {
     "title": "[AWS/ElastiCache] NetworkBytesOut",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_elasticache_network_bytes_out_average{cache_cluster_id=~\"${cache_cluster_prefix}.*\"})",
       "legendFormat": "{{cache_cluster_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "AWS/CloudFront",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "[AWS/CloudFront] Total Requests",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_cloudfront_requests_sum{distribution_id=\"$distribution_id\"})",
       "legendFormat": "quay"
      }
     ]
    },
    {
     "title": "[AWS/CloudFront] BytesUploaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_cloudfront_bytes_uploaded_sum{distribution_id=\"$distribution_id\"})",
       "legendFormat": "quay"
      }
     ]
    },
    {
     "title": "[AWS/CloudFront] BytesDownloaded",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_cloudfront_bytes_downloaded_sum{distribution_id=\"$distribution_id\"})",
       "legendFormat": "quay"
      }
     ]
    },
    {
     "title": "[AWS/CloudFront] 4xxErrorRate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_cloudfront_4xx_error_rate_average{distribution_id=\"$distribution_id\"})",
       "legendFormat": "quay"
      }
     ]
    },
    {
     "title": "[AWS/CloudFront] 5xxErrorRate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_cloudfront_5xx_error_rate_average{distribution_id=\"$distribution_id\"})",
       "legendFormat": "quay"
      }
     ]
    },
    {
     "title": "[AWS/CloudFront] TotalErrorRate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_cloudfront_total_error_rate_average{distribution_id=\"$distribution_id\"})",
       "legendFormat": "quay"
      }
     ]
    }
   ]
  },
  {
   "title": "AWS/RDS (apostille)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "[AWS/RDS] CPUUtilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_cpuutilization_average{dbinstance_identifier=\"$apostille_db\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Database Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none", "label": "Database Connections" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_database_connections_average{dbinstance_identifier=\"$apostille_db\"})",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Read/Write IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_read_iops_average{dbinstance_identifier=\"$apostille_db\"})",
       "legendFormat": "read"
      },
      {
       "expr": "max without(pod,instance) (aws_rds_write_iops_average{dbinstance_identifier=\"$apostille_db\"})",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Read/Write Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_read_latency_average{dbinstance_identifier=\"$apostille_db\"})",
       "legendFormat": "read"
      },
      {
       "expr": "max without(pod,instance) (aws_rds_write_latency_average{dbinstance_identifier=\"$apostille_db\"})",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "[AWS/RDS] Free Storage Space",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "max without(pod,instance) (aws_rds_free_storage_space_average{dbinstance_identifier=\"$apostille_db\"})",
       "legendFormat": "${apostille_db}"
      }
     ]
    }
   ]
  }
 ]
}