#!/bin/sh -eux
echo "Make sure you run this command with PIP_CONSTRAINT=constraints.txt"
curl -fsSLO https://raw.githubusercontent.com/containerbuildsystem/cachito/master/bin/pip_find_builddeps.py
pip-compile pyproject.toml -o requirements.in --generate-hashes --allow-unsafe
sed -i.bak '/^Cython<3.0/d' requirements.in
rm requirements-build.in.bak
python3 pip_find_builddeps.py requirements.in -o requirements-build.in -a
sed -i.bak '/^Cython<3.0/d' requirements-build.in
pip-compile requirements-build.in -o requirements-build.txt --allow-unsafe --generate-hashes
sed -i.bak '1i\
# This file is autogenerated by hack/update-requirements-build.sh.
/^cython==/a\
cython==3.0.2
' requirements-build.txt
rm requirements-build.txt.bak
