#!/bin/sh -eux
curl -fsSLO https://raw.githubusercontent.com/containerbuildsystem/cachito/master/bin/pip_find_builddeps.py
python3 pip_find_builddeps.py requirements.txt -o requirements-build.in
sed -i.bak '/^Cython>=3.0.2/d' requirements-build.in
rm requirements-build.in.bak
pip-compile -q requirements-build.in -o requirements-build.txt --allow-unsafe
python3 pip_find_builddeps.py requirements-build.txt -o requirements-build.in -a
pip-compile -q requirements-build.in -o requirements-build.txt --allow-unsafe
sed -i.bak '1i\
# This file is autogenerated by hack/update-requirements-build.sh.
/^cython==/a\
cython==3.0.2
' requirements-build.txt
rm requirements-build.txt.bak
