#!/bin/sh -eu
# requirements.txt is generated by `hack/update-requirements.sh` (pip-compile
# --generate-hashes): every package, direct or transitive, is a fully pinned
# top-level entry with sha256 hashes. Installing it in pip's hash-checking
# mode is itself the verification that matters here -- pip fails loudly if
# any package is missing a hash, if a hash doesn't match the downloaded
# artifact, or if the pinned set doesn't actually resolve.
TMP=$(mktemp -d "${TMPDIR:-/tmp/}quay-verify-requirements.XXXXXXXX")
trap 'rc=$?; rm -rf "$TMP"; exit $rc' EXIT

pip install --require-hashes --target="$TMP/packages" -r ./requirements.txt
