#! /bin/bash

echo 'Starting nginx'

QUAYPATH=${QUAYPATH:-"."}
cd ${QUAYDIR:-"/"}
PYTHONPATH=$QUAYPATH
QUAYCONF=${QUAYCONF:-"$QUAYPATH/conf"}

/usr/sbin/nginx -c $QUAYDIR/config_app/conf/nginx.conf

echo 'Nginx exited'
