#! /bin/bash

echo 'Starting memcached'

if [ "$DEBUGLOG" == "true" ]
then
    memcached -u memcached -m 64 -vv -l 127.0.0.1 -p 18080
else
    memcached -u memcached -m 64 -l 127.0.0.1 -p 18080
fi

echo 'memcached exited'
