[package]
name = "quay"
version = "0.1.0"
edition = "2021"

[dependencies]
asn1 = { version = "0.21.3", default-features = false }
pyo3 = { version = "0.25", features = ["abi3"] }
pyo3-build-config = { version = "0.25" }
openssl = "0.10.72"
openssl-sys = "0.9.108"
