base_images:
  cli:
    name: "{{ ocp_version }}"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-9-release-golang-1.25-openshift-{{ ocp_version }}
images:
  items:
  - dockerfile_path: Dockerfile
    to: quay-server
  - dockerfile_path: web/Containerfile.playwright
    to: quay-playwright-runner
  skip_if_only_changed: ^(.agents/|.claude/|docs/|.*.md$)
{% if layout == "base" %}
promotion:
  to:
  - namespace: quay
    tag: latest
    tag_by_commit: true
{% endif %}
prowgen:
  enable_secrets_store_csi_driver: true
releases:
  latest:
    candidate:
      architecture: "{{ arch }}"
      product: ocp
      stream: nightly
      version: "{{ ocp_version }}"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: "{{ test_as }}"
  timeout: 4h0m0s
zz_generated_metadata:
  branch: "{{ branch }}"
  org: "{{ org }}"
  repo: "{{ repo }}"
{% if layout != "base" %}
  variant: "{{ variant }}"
{% endif %}
