style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/quay/quay
options:
  sort: semver
  commits:
    sort_by: Scope
  commit_groups:
    group_by: Scope
  header:
    #pattern: '^(.*):\s*(.*)\s*(.*)$'
    #pattern: '^(.*):\s*(.*)\s(\(PROJQUAY-[0-9]+\))(\s\(#[0-9]+\))?\n(\n(\n|.)*)?$'
    pattern: '^(.*):\s*(.*)\s(\(PROJQUAY-[0-9]+\))(\s\(#[0-9]+\))?$'
    pattern_maps:
      - Scope
      - Subject
      - Issue
      - PullRequest
  issues:
    prefix:
      - "#"

  refs:
    actions:
      - Closes
      - Fixes
      - PullRequest

  notes:
    keywords:
      - BREAKING CHANGE
      - NOTE
