// Package schema embeds SQLite DDL and seed data generated by make go-schema.
package schema

import (
	"embed"
)

// QuaySchemaSQL contains CREATE TABLE and CREATE INDEX statements for all Quay tables.
//
//go:embed sqlite/quay_schema.sql
var QuaySchemaSQL string

// SeedDataSQL contains INSERT statements for enum/lookup tables (role, mediatype, etc.).
//
//go:embed sqlite/seed_data.sql
var SeedDataSQL string

// MigrationFiles contains SQLite migration files.
// Bridge migrations include a "-- revision: <id>" comment. Chainable
// SQLite migrations also include "-- down_revision: <id>".
//
//go:embed sqlite/migrations
var MigrationFiles embed.FS
