// Package schema embeds SQLite DDL and seed data generated by make go-schema.
package schema

import (
	"embed"
)

// QuaySchemaSQL contains CREATE TABLE and CREATE INDEX statements for all Quay tables.
//
//go:embed sqlite/quay_schema.sql
var QuaySchemaSQL string

// SeedDataSQL contains INSERT statements for enum/lookup tables (role, mediatype, etc.).
//
//go:embed sqlite/seed_data.sql
var SeedDataSQL string

// CompatibilitySQL embeds the OMR/Alembic compatibility SQL used to bridge a
// supported historical SQLite schema onto this binary's target revision. See
// internal/dal/dbcore/bridge.go for the explicit accepted source revision
// and the single compatibility step applied against it.
//
//go:embed sqlite/compatibility
var CompatibilitySQL embed.FS

// OMRSourceSchemaSQL is the approved OMR v2 intermediate schema.
//
//go:embed sqlite/omr/3f8d7acdf7f9_schema.sql
var OMRSourceSchemaSQL string

// OMRSourceSeedDataSQL seeds the approved OMR v2 intermediate.
//
//go:embed sqlite/omr/3f8d7acdf7f9_seed_data.sql
var OMRSourceSeedDataSQL string
