apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/quay/quay?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push"
      && target_branch == "master"
      && (
        "requirements.txt".pathChanged()
        || "requirements-build.txt".pathChanged()
        || "Dockerfile.downstream".pathChanged()
        || "rpms.in.yaml".pathChanged()
        || "rpms.lock.yaml".pathChanged()
        || "ubi.repo".pathChanged()
        || "artifacts.lock.yaml".pathChanged()
        || "rust-builddeps/***".pathChanged()
        || ".tekton/quay-hermetic-push.yaml".pathChanged()
      )
    pipelinesascode.tekton.dev/target-namespace: "quay-eng-tenant"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: quay-hermetic
    appstudio.openshift.io/component: quay-hermetic
    pipelines.appstudio.openshift.io/type: build
  name: quay-hermetic-on-push
  namespace: quay-eng-tenant
spec:
  timeouts:
    pipeline: 3h
  taskRunSpecs:
    - pipelineTaskName: build-images
      stepSpecs:
        - name: build
          computeResources:
            requests:
              memory: '32Gi'
              cpu: '8000m'
            limits:
              memory: '32Gi'
              cpu: '8000m'
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/quay-eng-tenant/quay-hermetic/quay-hermetic:{{revision}}
  - name: dockerfile
    value: Dockerfile.downstream
  - name: path-context
    value: .
  - name: hermetic
    value: "true"
  - name: prefetch-input
    value: |
      [
        {"type": "gomod", "path": "./config-tool"},
        {"type": "pip", "path": "."},
        {"type": "npm", "path": "./web"},
        {"type": "npm", "path": "."},
        {"type": "rpm", "path": "."},
        {"type": "cargo", "path": "./rust-builddeps"}
      ]
  - name: slack-notification-on-failure
    value: "true"
  pipelineRef:
    name: build-quay-image
  taskRunTemplate:
    serviceAccountName: build-pipeline-quay-hermetic
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
