"""Add expriy for robot token

Revision ID: 3be1fc2915df
Revises: 2664723e1b4b
Create Date: 2024-07-03 22:45:07.889575

"""

# revision identifiers, used by Alembic.
revision = "3be1fc2915df"
down_revision = "2664723e1b4b"

import sqlalchemy as sa


def upgrade(op, tables, tester):
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("robotaccounttoken", sa.Column("expiration", sa.DateTime(), nullable=True))
    op.create_index(
        "robot_account_token_expiration", "robotaccounttoken", ["expiration"], unique=False
    )


def downgrade(op, tables, tester):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("robot_account_token_expiration", table_name="robotaccounttoken")
    op.drop_column("expiration")
