"""
Add index on logs_archived on repositorybuild.

Revision ID: 481623ba00ba
Revises: b9045731c4de
Create Date: 2019-02-15 16:09:47.326805
"""

# revision identifiers, used by Alembic.
revision = "481623ba00ba"
down_revision = "b9045731c4de"


def upgrade(op, tables, tester):
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "repositorybuild_logs_archived", "repositorybuild", ["logs_archived"], unique=False
    )
    # ### end Alembic commands ###


def downgrade(op, tables, tester):
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("repositorybuild_logs_archived", table_name="repositorybuild")
    # ### end Alembic commands ###
