apiVersion: v1
kind: Template
metadata:
  name: quayio-frontend
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: quay
    spec:
      feoConfigEnabled: true
      envName: ${ENV_NAME}
      title: Quay.io
      deploymentRepo: https://github.com/quay/quay
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/quay
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - appId: "quay"
          title: "Quay.io"
          href: "/quay/organization"
          product: "Red Hat Quay.io"
      bundleSegments:
        - segmentId: quay-main
          bundleId: quay
          position: 100
          navItems:
            - id: quayOverview
              title: Overview
              href: /quay/overview
            - id: quayOrganizations
              title: Organizations
              href: /quay/organization
            - id: quayRepositories
              title: Repositories
              href: /quay/repository
      widgetRegistry:
        - scope: "landing"
          module: "./QuayWidget"
          defaults:
            w: 1
            h: 4
            maxH: 10
            minH: 1
          config:
            title: "Quay.io"
            icon: "QuayIcon"
      module:
        manifestLocation: "/apps/quay/fed-mods.json"
        modules:
          - id: "quay"
            module: "./QuayPluginMain"
            routes:
              - pathname: /quay/overview
              - pathname: /quay/organization
              - pathname: /quay/repository
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/app-sre/quayio-frontend
