FEATURE_GITHUB_LOGIN: true
GITHUB_LOGIN_CONFIG:
  CLIENT_ID: "mock-github-client-id"
  CLIENT_SECRET: "mock-github-client-secret"
  GITHUB_ENDPOINT: "http://host.containers.internal:9090"
  API_ENDPOINT: "http://host.containers.internal:9090/api/v3/"
